/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlyquanan.view.VoucherMgt;

import com.mycompany.quanlyquanan.controller.VoucherController;
import com.mycompany.quanlyquanan.model.ModelVoucher;
import com.mycompany.quanlyquanan.utils.ComponentStyleUtil;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 * @author macos
 */
public class EditVoucherFrame extends javax.swing.JFrame {

    /**
     * Creates new form EditVoucherFrame
     */
    private ModelVoucher voucher;
//    VoucherService vcService;
    VoucherController vcController;
    Runnable onUpdateSuccess; // Callback function


    public EditVoucherFrame(int voucherId, Runnable onUpdateSuccess) {
        vcController = new VoucherController();
        voucher = vcController.getVoucherById(voucherId);
        this.onUpdateSuccess = onUpdateSuccess;
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        voucherIdTextField.setText(String.valueOf(voucher.getId()));
        vcCodeTextField.setText(voucher.getVoucherCode());
        descriptionTextArea.setText(voucher.getDescription());
        percentageTextField.setText(String.valueOf(voucher.getPercentage()));
        quantityTextField.setText(String.valueOf(voucher.getQuantity()));
        // Convert java.util.Date -> LocalDate
        if (voucher.getStartDate() != null) {
            startDateField.setDate(((java.sql.Date) voucher.getStartDate()).toLocalDate());
        }

        if (voucher.getEndDate() != null) {
            endDateField.setDate(((java.sql.Date) voucher.getEndDate()).toLocalDate());
        }

        // Apply consistent styling to components
        applyConsistentStyling();

    }
    
    public EditVoucherFrame(int voucherId) {
        vcController = new VoucherController();
        voucher = vcController.getVoucherById(voucherId);
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        voucherIdTextField.setText(String.valueOf(voucher.getId()));
        vcCodeTextField.setText(voucher.getVoucherCode());
        descriptionTextArea.setText(voucher.getDescription());
        percentageTextField.setText(String.valueOf(voucher.getPercentage()));
        quantityTextField.setText(String.valueOf(voucher.getQuantity()));
        // Convert java.util.Date -> LocalDate
        if (voucher.getStartDate() != null) {
            startDateField.setDate(((java.sql.Date) voucher.getStartDate()).toLocalDate());
        }

        if (voucher.getEndDate() != null) {
            endDateField.setDate(((java.sql.Date) voucher.getEndDate()).toLocalDate());
        }

        // Apply consistent styling to components
        applyConsistentStyling();

    }

    public void applyConsistentStyling(){
        // Style input components
        ComponentStyleUtil.styleTextFields(vcCodeTextField, percentageTextField, quantityTextField);
        ComponentStyleUtil.styleTextArea(descriptionTextArea);
        ComponentStyleUtil.styleDatePickers(startDateField, endDateField);
        ComponentStyleUtil.styleMainButton(submitButton);
        ComponentStyleUtil.styleSecondButton(closeButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        submitButton = new com.mycompany.quanlyquanan.view.VoucherMgt.MyButtonMain();
        closeButton = new com.mycompany.quanlyquanan.view.VoucherMgt.MyButtonSecond();
        jPanel2 = new javax.swing.JPanel();
        voucherId = new javax.swing.JLabel();
        voucherIdTextField = new javax.swing.JTextField();
        vcCode = new javax.swing.JLabel();
        vcCodeTextField = new javax.swing.JTextField();
        description = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        percentage = new javax.swing.JLabel();
        percentageTextField = new javax.swing.JTextField();
        quantityTextField = new javax.swing.JTextField();
        quantity = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        startDateField = new com.github.lgooddatepicker.components.DatePicker();
        endDateField = new com.github.lgooddatepicker.components.DatePicker();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 661));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 100));

        submitButton.setText("Sửa");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Hủy");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 450));

        voucherId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        voucherId.setText("Voucher ID");
        voucherId.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        voucherId.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        voucherId.setPreferredSize(new java.awt.Dimension(72, 24));
        voucherId.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        voucherIdTextField.setEnabled(false);
        voucherIdTextField.setMinimumSize(new java.awt.Dimension(64, 24));

        vcCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vcCode.setText("Voucher Code");
        vcCode.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        vcCode.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        vcCode.setPreferredSize(new java.awt.Dimension(92, 24));
        vcCode.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        vcCodeTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        vcCodeTextField.setToolTipText("Nhập");

        description.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        description.setText("Description");
        description.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        description.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        description.setPreferredSize(new java.awt.Dimension(72, 24));
        description.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setLineWrap(true);
        descriptionTextArea.setRows(5);
        descriptionTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        descriptionTextArea.setOpaque(false);
        descriptionTextArea.setPreferredSize(new java.awt.Dimension(600, 90));
        jScrollPane1.setViewportView(descriptionTextArea);

        percentage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        percentage.setText("Percentage");
        percentage.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        percentage.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        percentage.setPreferredSize(new java.awt.Dimension(74, 24));
        percentage.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        percentageTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        quantityTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        quantity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        quantity.setText("Quantity");
        quantity.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        quantity.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        quantity.setPreferredSize(new java.awt.Dimension(53, 24));
        quantity.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Start Date");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(64, 24));
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        startDateField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        endDateField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("End Date");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(59, 24));
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vcCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(description, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(percentage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(voucherId, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(percentageTextField)
                    .addComponent(jScrollPane1)
                    .addComponent(vcCodeTextField)
                    .addComponent(quantityTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(voucherIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voucherId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voucherIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vcCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vcCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(percentageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Voucher");
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(600, 76));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        try {
            String vcCode = vcCodeTextField.getText();
            String description = descriptionTextArea.getText();
            String percentage = percentageTextField.getText();
            String quantity = quantityTextField.getText();
            LocalDate startDateLocale = startDateField.getDate();
            LocalDate endDateLocale = endDateField.getDate();

            // Kiểm tra các trường bắt buộc
            if (vcCode.isEmpty()){
                JOptionPane.showMessageDialog(this, "Voucher Code không được để trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (description.isEmpty()){
                JOptionPane.showMessageDialog(this, "Description không được để trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (percentage.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Percentage không được để trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if(!percentage.matches("\\d+(\\.\\d+)?")){
                JOptionPane.showMessageDialog(this, "Percentage phải là số hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;

            }

            if(quantity.isEmpty()){
                JOptionPane.showMessageDialog(this, "Quantity không được để trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if(!quantity.matches("\\d+")){
                JOptionPane.showMessageDialog(this, "Quantity phải là số nguyên dương!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (startDateLocale == null) {
                JOptionPane.showMessageDialog(this, "Start Date không được để trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (endDateLocale == null) {
                JOptionPane.showMessageDialog(this, "End Date không được để trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (endDateLocale.isBefore(startDateLocale)) {
                JOptionPane.showMessageDialog(this, "End Date phải sau Start Date!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Kiểm tra voucher code có tồn tại hay không
            if (vcController.isVoucherCodeExists(vcCode)) {
                JOptionPane.showMessageDialog(this, "Voucher Code đã tồn tại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

           // Nếu tất cả các trường hợp kiểm tra đều hợp lệ, tiến hành cập nhật voucher
            // Convert sang java.util.Date (nếu Voucher dùng Date)
            Date startDate = Date.from(startDateLocale.atStartOfDay(ZoneId.systemDefault()).toInstant());
            Date endDate = Date.from(endDateLocale.atStartOfDay(ZoneId.systemDefault()).toInstant());

            voucher.setVoucherCode(vcCodeTextField.getText());
            voucher.setDescription(descriptionTextArea.getText());
            voucher.setPercentage(Double.valueOf(percentageTextField.getText()));
            voucher.setQuantity(Integer.valueOf(quantityTextField.getText()));
            voucher.setStartDate(startDate);
            voucher.setEndDate(endDate);
        } catch (Exception e) {
            e.printStackTrace();
        }

        vcController.updateVoucher(voucher);
        // TODO nhớ chỉnh lại Frame nào cần back lại
//        new Main().setVisible(true);
        if (onUpdateSuccess != null) {
            onUpdateSuccess.run(); // Gọi hàm callback để thông báo cập nhật thành công
        }
        this.dispose();
        JOptionPane.showMessageDialog(EditVoucherFrame.this, "Cập nhật voucher thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
    }

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EditVoucherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EditVoucherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EditVoucherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EditVoucherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EditVoucherFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.quanlyquanan.view.VoucherMgt.MyButtonSecond closeButton;
    private javax.swing.JLabel description;
    private javax.swing.JTextArea descriptionTextArea;
    private com.github.lgooddatepicker.components.DatePicker endDateField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel percentage;
    private javax.swing.JTextField percentageTextField;
    private javax.swing.JLabel quantity;
    private javax.swing.JTextField quantityTextField;
    private com.github.lgooddatepicker.components.DatePicker startDateField;
    private com.mycompany.quanlyquanan.view.VoucherMgt.MyButtonMain submitButton;
    private javax.swing.JLabel vcCode;
    private javax.swing.JTextField vcCodeTextField;
    private javax.swing.JLabel voucherId;
    private javax.swing.JTextField voucherIdTextField;
    // End of variables declaration//GEN-END:variables
}
