/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/OkCancelDialog.java to edit this template
 */
package com.mycompany.quanlyquanan.view.Employee;

import com.mycompany.quanlyquanan.controller.EmployeeController;
import com.mycompany.quanlyquanan.model.Employee;
import com.mycompany.quanlyquanan.utils.ComponentStyleUtil;
import com.mycompany.quanlyquanan.utils.HashUtil;
import com.mycompany.quanlyquanan.utils.ImageUtils;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Admin
 */
public class EditEmployeeDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditEmployeeDialog.class.getName());

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form CreateEmployeeDialog
     */
    private QuanLyNhanVienPanel parentPanel;
    private Employee selectedEmp;
    private String savedImagePath = null;
    private EmployeeController controller = new EmployeeController();

    public EditEmployeeDialog(java.awt.Frame parent, boolean modal, QuanLyNhanVienPanel parentPanel, Employee emp) {
        super(parent, modal);
        initComponents();
        this.parentPanel = parentPanel;
        this.selectedEmp = emp;
        loadData(emp);

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
        ComponentStyleUtil.styleMainButton(bntAdd);
        ComponentStyleUtil.styleSecondButton(btnCancel);
    }

    private void loadData(Employee emp) {
        ipName.setText(emp.getName());
        ipUserName.setText(emp.getUsername());
        ipPhone.setText(emp.getPhone());
        ipEmail.setText(emp.getEmail());
        ipAdd.setText(emp.getAddress());
        ipPosition.setText(emp.getPosition());
        ipRole.setSelectedItem(emp.getRole());

        // Hiển thị ảnh
        if (emp.getAvatar() != null && !emp.getAvatar().isEmpty()) {
            ImageIcon icon = new ImageIcon(emp.getAvatar());
            Image img = icon.getImage().getScaledInstance(160, 160, Image.SCALE_SMOOTH);
            ipAvatar.setIcon(new ImageIcon(img));
        } else {
            ImageIcon icon = new ImageIcon("assets/images/employee/default.png");
            Image img = icon.getImage().getScaledInstance(160, 160, Image.SCALE_SMOOTH);
            ipAvatar.setIcon(new ImageIcon(img));

        }
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnProfile = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ipAvatar = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ipPhone = new javax.swing.JTextField();
        ipAdd = new javax.swing.JTextField();
        ipEmail = new javax.swing.JTextField();
        ipRole = new javax.swing.JComboBox<>();
        btnThemAnh = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        bntAdd = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ipName = new javax.swing.JTextField();
        ipUserName = new javax.swing.JTextField();
        ipPosition = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnProfile.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Edit User");

        ipAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/employee/coala-160.png"))); // NOI18N
        ipAvatar.setText("jLabel12");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Họ tên:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Vị trí:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Role:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Điện thoại: ");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Địa chỉ:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Email:");

        ipAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel15)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ipEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ipAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ipPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(ipPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(ipAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(ipEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        ipRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Nhân Viên", "Bếp", "Thu Ngân" }));
        ipRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipRoleActionPerformed(evt);
            }
        });

        btnThemAnh.setText("Thêm ảnh");
        btnThemAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemAnhMouseClicked(evt);
            }
        });
        btnThemAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemAnhActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 51, 51));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Hủy");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        bntAdd.setBackground(new java.awt.Color(0, 153, 0));
        bntAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntAdd.setForeground(new java.awt.Color(255, 255, 255));
        bntAdd.setText("Sửa");
        bntAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntAddMouseClicked(evt);
            }
        });
        bntAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAddActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("User name");

        jLabel1.setText("* Kích thước ảnh tối đa 160*160");

        ipName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipNameActionPerformed(evt);
            }
        });

        ipUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipUserNameActionPerformed(evt);
            }
        });

        ipPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipPositionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnProfileLayout = new javax.swing.GroupLayout(pnProfile);
        pnProfile.setLayout(pnProfileLayout);
        pnProfileLayout.setHorizontalGroup(
            pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfileLayout.createSequentialGroup()
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnProfileLayout.createSequentialGroup()
                        .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnProfileLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ipAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(pnProfileLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(btnThemAnh)))
                        .addGap(34, 34, 34)
                        .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProfileLayout.createSequentialGroup()
                                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel25))
                                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnProfileLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(ipRole, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel23)
                                        .addGap(18, 18, 18)
                                        .addComponent(ipPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnProfileLayout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(ipName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnProfileLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(ipUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnProfileLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(bntAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProfileLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(291, 291, 291))
        );
        pnProfileLayout.setVerticalGroup(
            pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfileLayout.createSequentialGroup()
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnProfileLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(ipAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThemAnh))
                    .addGroup(pnProfileLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel11)
                        .addGap(33, 33, 33)
                        .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(ipName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(ipUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(ipRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(ipPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        getContentPane().add(pnProfile, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void ipRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipRoleActionPerformed

    private void btnThemAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemAnhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemAnhActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void bntAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntAddActionPerformed

    private void ipNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipNameActionPerformed

    private void ipPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipPositionActionPerformed

    private void ipUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipUserNameActionPerformed

    private void ipAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipAddActionPerformed

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnThemAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemAnhMouseClicked
        File file = ImageUtils.chooseImageFile(this);
        if (file != null) {
            selectedImageFile = file;
            // Hiển thị ảnh lên label
            ImageIcon icon = new ImageIcon(file.getAbsolutePath());
            Image scaledImage = icon.getImage().getScaledInstance(160, 160, Image.SCALE_SMOOTH);
            ipAvatar.setIcon(new ImageIcon(scaledImage));
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemAnhMouseClicked

    private void bntAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntAddMouseClicked
        // TODO add your handling code here:

        if (!isChanged(selectedEmp)) {
            JOptionPane.showMessageDialog(this, "Không có thay đổi mới");
            return;
        }

        String name = ipName.getText().trim();
        String role = (String) ipRole.getSelectedItem();
        String userName = ipUserName.getText().trim();
        String position = ipPosition.getText().trim();
        String phone = ipPhone.getText().trim();
        String add = ipAdd.getText().trim();
        String email = ipEmail.getText().trim();

        if (name.isEmpty()
                || role.isEmpty()
                || userName.isEmpty()
                || position.isEmpty()
                || phone.isEmpty()
                || add.isEmpty()
                || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống!");
            return;
        }
        if (selectedImageFile != null) {
            try {
                savedImagePath = ImageUtils.saveImage(selectedImageFile, "assets/images/employee/");
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi lưu ảnh", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        Employee emp = new Employee();
        emp.setId(selectedEmp.getId());
        emp.setName(name);
        emp.setRole(role);
        if (selectedImageFile != null) {
            emp.setAvatar(savedImagePath);
        }
        emp.setUsername(userName);
        emp.setPosition(position);
        emp.setPhone(phone);
        emp.setAddress(add);
        emp.setPass(selectedEmp.getPass());
        emp.setEmail(email);
        emp.setActive(selectedEmp.isActive());

        if (controller.update(emp)) {
            JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thành công!");
                List<Employee> employees = controller.getAll();
            parentPanel.loadTable(employees); // Gọi lại bảng danh sách
            this.dispose(); // Đóng dialog
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thất bại!");
        }


    }//GEN-LAST:event_bntAddMouseClicked

    private boolean isChanged(Employee emp) {

        String name = ipName.getText().trim();
        String role = (String) ipRole.getSelectedItem();
        String userName = ipUserName.getText().trim();
        String position = ipPosition.getText().trim();
        String phone = ipPhone.getText().trim();
        String add = ipAdd.getText().trim();
        String email = ipEmail.getText().trim();
        if (!Objects.equals(emp.getName(), name)) {
            return true;
        }
        if (!Objects.equals(emp.getRole(), role)) {
            return true;
        }
        if (!Objects.equals(emp.getUsername(), userName)) {
            return true;
        }
        if (!Objects.equals(emp.getPosition(), position)) {
            return true;
        }
        if (!Objects.equals(emp.getPhone(), phone)) {
            return true;
        }
        if (!Objects.equals(emp.getAddress(), add)) {
            return true;
        }
        if (!Objects.equals(emp.getEmail(), email)) {
            return true;
        }
        if(selectedImageFile != null){
            return true;
        }
        return false;
    }

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }
    private File selectedImageFile = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnThemAnh;
    private javax.swing.JTextField ipAdd;
    private javax.swing.JLabel ipAvatar;
    private javax.swing.JTextField ipEmail;
    private javax.swing.JTextField ipName;
    private javax.swing.JTextField ipPhone;
    private javax.swing.JTextField ipPosition;
    private javax.swing.JComboBox<String> ipRole;
    private javax.swing.JTextField ipUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnProfile;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
