/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/OkCancelDialog.java to edit this template
 */
package com.mycompany.quanlyquanan.view.recipe;

import com.mycompany.quanlyquanan.controller.RecipeController;
import com.mycompany.quanlyquanan.model.Dish;
import com.mycompany.quanlyquanan.model.Material;
import com.mycompany.quanlyquanan.model.Recipe;
import com.mycompany.quanlyquanan.utils.ComponentStyleUtil;

import java.awt.Frame;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;


public class CreateRecipeDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateRecipeDialog.class.getName());
    
    private final RecipeController recipeController = new RecipeController();
    private final List<Dish> dishes = new ArrayList<>();
    private final List<Material> materials = new ArrayList<>();
    private final QuanLyCongThucPanel parentPanel;

    public CreateRecipeDialog(java.awt.Frame parent, boolean modal, QuanLyCongThucPanel parentPanel) {
        super(parent, modal);
        initComponents();
        this.parentPanel = parentPanel;
        loadDishes();
        loadMaterials();
        setupListeners();
        updateMaterialInfo();
        ComponentStyleUtil.styleMainButton(bntAdd);
        ComponentStyleUtil.styleSecondButton(btnCancel);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gMerge = new javax.swing.ButtonGroup();
        pnProfile = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        bntAdd = new javax.swing.JButton();
        cboDish = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        ipMaterial = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        ipQuantity = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        ipUnit = new javax.swing.JTextField();
        lblTotalCost = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        lblMaterialPrice = new javax.swing.JTextField();
        lblUnit = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnProfile.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Thêm Công thức mới");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Món Ăn:");

        btnCancel.setBackground(new java.awt.Color(255, 51, 51));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Hủy");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        bntAdd.setBackground(new java.awt.Color(0, 153, 0));
        bntAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntAdd.setForeground(new java.awt.Color(255, 255, 255));
        bntAdd.setText("Thêm");
        bntAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntAddMouseClicked(evt);
            }
        });
        bntAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAddActionPerformed(evt);
            }
        });

        cboDish.setEditable(true);
        cboDish.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDish.setMinimumSize(new java.awt.Dimension(72, 16));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Nguyên Liệu:");

        ipMaterial.setEditable(true);
        ipMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ipMaterial.setMinimumSize(new java.awt.Dimension(72, 16));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Số Lượng:");

        ipQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipQuantityActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Giá Nguyên Liệu:");

        ipUnit.setEditable(false);
        ipUnit.setBackground(new java.awt.Color(255, 255, 255));
        ipUnit.setForeground(new java.awt.Color(153, 153, 153));
        ipUnit.setText("kg");
        ipUnit.setBorder(null);
        ipUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipUnitActionPerformed(evt);
            }
        });

        lblTotalCost.setEditable(false);
        lblTotalCost.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalCost.setForeground(new java.awt.Color(0, 153, 51));
        lblTotalCost.setText("10.000");
        lblTotalCost.setBorder(null);
        lblTotalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblTotalCostActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("Thành Tiền:");

        lblMaterialPrice.setEditable(false);
        lblMaterialPrice.setBackground(new java.awt.Color(255, 255, 255));
        lblMaterialPrice.setForeground(new java.awt.Color(153, 153, 153));
        lblMaterialPrice.setText("10.000 VNĐ/đơn vị");
        lblMaterialPrice.setBorder(null);
        lblMaterialPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblMaterialPriceActionPerformed(evt);
            }
        });

        lblUnit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUnit.setForeground(new java.awt.Color(153, 153, 153));
        lblUnit.setText("Đơn vị:");

        javax.swing.GroupLayout pnProfileLayout = new javax.swing.GroupLayout(pnProfile);
        pnProfile.setLayout(pnProfileLayout);
        pnProfileLayout.setHorizontalGroup(
            pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfileLayout.createSequentialGroup()
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnProfileLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnProfileLayout.createSequentialGroup()
                                .addComponent(bntAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(175, 175, 175)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnProfileLayout.createSequentialGroup()
                                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnProfileLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboDish, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnProfileLayout.createSequentialGroup()
                                        .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel18))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnProfileLayout.createSequentialGroup()
                                                .addComponent(ipQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblUnit)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ipUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(ipMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnProfileLayout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(pnProfileLayout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnProfileLayout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblMaterialPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(46, 46, 46))))
                    .addGroup(pnProfileLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel11)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        pnProfileLayout.setVerticalGroup(
            pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfileLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addGap(39, 39, 39)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(cboDish, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(ipMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ipUnit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ipQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)
                        .addComponent(lblUnit)))
                .addGap(18, 18, 18)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(lblMaterialPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(lblTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(pnProfile, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        dispose();
    }//GEN-LAST:event_closeDialog

    private void bntAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAddActionPerformed
        Material selectedMaterial = (Material) ipMaterial.getSelectedItem();
        Dish selectedDish = (Dish) cboDish.getSelectedItem();
        if (selectedMaterial == null || selectedDish == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn món ăn và nguyên liệu", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        BigDecimal quantity;
        try {
            quantity = new BigDecimal(ipQuantity.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Số lượng không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (recipeController.createWithValidation(selectedDish.getId(), selectedMaterial.getId(), quantity)) {
            if (parentPanel != null) {
                parentPanel.loadRecipes();
            }
            dispose();
        }
    }//GEN-LAST:event_bntAddActionPerformed

    private void bntAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntAddMouseClicked
        /*
        Recipe selectedRecipe = (Recipe) ipMaterial.getSelectedItem();
        Dish selectedDish = (Dish) cboDish.getSelectedItem();
        if (selectedRecipe == null || selectedDish == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn món ăn và nguyên liệu", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        BigDecimal quantity;
        try {
            quantity = new BigDecimal(ipQuantity.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Số lượng không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (recipeController.updateWithValidation(selectedRecipe.getId(), selectedDish.getId(), selectedRecipe.getMaterialId(), quantity)) {
            if (parentPanel != null) {
                parentPanel.loadRecipes();
            }
            dispose();
        }
        */
        bntAddActionPerformed(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_bntAddMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
  
    }//GEN-LAST:event_btnCancelMouseClicked

    private void ipQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipQuantityActionPerformed
        // TODO add your handling code here:
        updateTotalCost();
    }//GEN-LAST:event_ipQuantityActionPerformed

    private void ipUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipUnitActionPerformed

    private void lblTotalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblTotalCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTotalCostActionPerformed

    private void lblMaterialPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblMaterialPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMaterialPriceActionPerformed

    private void loadDishes() {
        dishes.clear();
        dishes.addAll(recipeController.getAvailableDishes());
        DefaultComboBoxModel model = new DefaultComboBoxModel(dishes.toArray());
        cboDish.setModel(model);
    }

    private void loadMaterials() {
        materials.clear();
        materials.addAll(recipeController.getActiveMaterials());
        DefaultComboBoxModel model = new DefaultComboBoxModel(materials.toArray());
        ipMaterial.setModel(model);
        ipMaterial.setRenderer(new DefaultListCellRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Material m) {
                    setText(m.getName());
                }
                return this;
            }
        });
    }

    private void setupListeners() {
        ipMaterial.addActionListener(e -> updateMaterialInfo());
        ipQuantity.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateTotalCost();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateTotalCost();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateTotalCost();
            }
        });
    }

    private void updateMaterialInfo() {
        Material m = (Material) ipMaterial.getSelectedItem();
        if (m != null) {
            ipUnit.setText(m.getUnit());
            lblMaterialPrice.setText(formatPrice(m.getPricePerUnit()) + "/đơn vị");
        } else {
            ipUnit.setText("");
            lblMaterialPrice.setText("");
        }
        updateTotalCost();
    }

    private void updateTotalCost() {
        Material m = (Material) ipMaterial.getSelectedItem();
        if (m == null) {
            lblTotalCost.setText("");
            return;
        }
        try {
            BigDecimal qty = new BigDecimal(ipQuantity.getText().trim());
            if (qty.compareTo(BigDecimal.ZERO) < 0) {
                lblTotalCost.setText("");
                return;
            }
            BigDecimal total = m.getPricePerUnit().multiply(qty);
            lblTotalCost.setText(formatPrice(total));
        } catch (Exception e) {
            lblTotalCost.setText("");
        }
    }

    private String formatPrice(BigDecimal price) {
        return String.format("%,.0f VNĐ", price);
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cboDish;
    private javax.swing.ButtonGroup gMerge;
    private javax.swing.JComboBox<String> ipMaterial;
    private javax.swing.JTextField ipQuantity;
    private javax.swing.JTextField ipUnit;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JTextField lblMaterialPrice;
    private javax.swing.JTextField lblTotalCost;
    private javax.swing.JLabel lblUnit;
    private javax.swing.JPanel pnProfile;
    // End of variables declaration//GEN-END:variables


}
