/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlyquanan.view.inventory;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.table.JTableHeader;
    
import com.mycompany.quanlyquanan.controller.MaterialController;
import com.mycompany.quanlyquanan.model.Material;
import com.mycompany.quanlyquanan.service.MaterialService;
import com.mycompany.quanlyquanan.utils.ComponentStyleUtil;
import com.mycompany.quanlyquanan.view.inventory.LichSuKhoPanel;
import com.mycompany.quanlyquanan.view.inventory.XuatKhoDialog;
import com.mycompany.quanlyquanan.view.material.ThemNguyenLieuDialog;
import com.mycompany.quanlyquanan.view.material.SuaNguyenLieuDialog;
import java.awt.Component;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Administrator
 */
public class QuanLyKhoPanel extends javax.swing.JPanel {
    

    // Added fields
    private final MaterialService materialService = new MaterialService();
    private final MaterialController materialController = new MaterialController();
    private List<Material> materials = new ArrayList<>();
    private Material selectedMaterial;
    private DefaultTableModel materialTableModel;
    
    private javax.swing.JFrame historyFrame;
    private LichSuKhoPanel historyPanel;
    
    private static final Color WARNING_COLOR = new Color(255, 193, 7);
    private static final Color DANGER_COLOR = new Color(220, 53, 69);


    public QuanLyKhoPanel() {

        initComponents();
        //customsStyle();
        styleSummaryTextFields();

        // Initialize table and data
        initTable();
        setupTableSelection();
        loadAllMaterials();

        // Add listeners for statistic cards
        jButton3.addActionListener(e -> showLowStockMaterials());
        btnHetHang.addActionListener(e -> showOutOfStockMaterials());
        ComponentStyleUtil.styleTableScrollPane(jScrollPane1);
        ComponentStyleUtil.styleTable(jTable1);
        ComponentStyleUtil.enableTableSorting(jTable1);
        ComponentStyleUtil.styleSearchTextField(ipSearch);
        ComponentStyleUtil.styleMainButton(btnNhapKho);
        //ComponentStyleUtil.styleMainButton(btnReport);
        ComponentStyleUtil.styleMainButton(btnRecord);
        ComponentStyleUtil.styleMainButton(btnXuatKho);
        
        btnSearch.addActionListener(e -> searchMaterials());
      
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChiTietNguyenLieu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        txtThread = new javax.swing.JTextField();
        txtValue = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnNhapKho = new javax.swing.JButton();
        btnRecord = new javax.swing.JButton();
        btnXuatKho = new javax.swing.JButton();
        jHeader = new javax.swing.JPanel();
        ipSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtcount = new javax.swing.JTextField();
        btncount = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtSapHet = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtHetHang = new javax.swing.JTextField();
        btnHetHang = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(244, 244, 244));
        setPreferredSize(new java.awt.Dimension(1219, 739));

        ChiTietNguyenLieu.setBackground(new java.awt.Color(255, 255, 255));
        ChiTietNguyenLieu.setPreferredSize(new java.awt.Dimension(300, 150));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Chi Tiết Nguyên Liệu");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtID.setForeground(new java.awt.Color(153, 153, 153));
        txtID.setText("ID:");
        txtID.setBorder(null);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        txtQty.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtQty.setForeground(new java.awt.Color(153, 153, 153));
        txtQty.setText("Số lượng:");
        txtQty.setBorder(null);
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });

        txtThread.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtThread.setForeground(new java.awt.Color(153, 153, 153));
        txtThread.setText("Ngưỡng tối thiểu:");
        txtThread.setBorder(null);
        txtThread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThreadActionPerformed(evt);
            }
        });

        txtValue.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtValue.setForeground(new java.awt.Color(153, 153, 153));
        txtValue.setText("Giá trị:");
        txtValue.setBorder(null);
        txtValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValueActionPerformed(evt);
            }
        });

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(102, 102, 102));
        txtName.setText("Bánh Phở");
        txtName.setBorder(null);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ChiTietNguyenLieuLayout = new javax.swing.GroupLayout(ChiTietNguyenLieu);
        ChiTietNguyenLieu.setLayout(ChiTietNguyenLieuLayout);
        ChiTietNguyenLieuLayout.setHorizontalGroup(
            ChiTietNguyenLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChiTietNguyenLieuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(ChiTietNguyenLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(txtThread, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(txtQty)
                    .addComponent(txtID)
                    .addComponent(txtValue)
                    .addComponent(txtName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ChiTietNguyenLieuLayout.setVerticalGroup(
            ChiTietNguyenLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChiTietNguyenLieuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtThread, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 497));

        jScrollPane1.setBorder(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 402));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên Nguyên Liệu", "Đơn vị","Số lượng", "Giá/đơn vị","Ngưỡng", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnNhapKho.setBackground(new java.awt.Color(0, 153, 0));
        btnNhapKho.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnNhapKho.setForeground(new java.awt.Color(255, 255, 255));
        btnNhapKho.setText("Nhập Kho");
        btnNhapKho.setPreferredSize(new java.awt.Dimension(150, 40));
        btnNhapKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhapKhoMouseClicked(evt);
            }
        });
        btnNhapKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapKhoActionPerformed(evt);
            }
        });

        btnRecord.setBackground(new java.awt.Color(0, 153, 153));
        btnRecord.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnRecord.setText("Lịch Sử Xuất/Nhập Kho");
        btnRecord.setPreferredSize(new java.awt.Dimension(187, 40));
        btnRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecordMouseClicked(evt);
            }
        });
        btnRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordActionPerformed(evt);
            }
        });

        btnXuatKho.setBackground(new java.awt.Color(255, 153, 0));
        btnXuatKho.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnXuatKho.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatKho.setText("Xuất Kho");
        btnXuatKho.setPreferredSize(new java.awt.Dimension(150, 40));
        btnXuatKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXuatKhoMouseClicked(evt);
            }
        });
        btnXuatKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatKhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnNhapKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXuatKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhapKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jHeader.setBackground(new java.awt.Color(255, 255, 255));
        jHeader.setPreferredSize(new java.awt.Dimension(1050, 212));

        ipSearch.setPreferredSize(new java.awt.Dimension(200, 40));
        ipSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipSearchActionPerformed(evt);
            }
        });
        ipSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ipSearchKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel1.setText("Quản Lý Kho");

        jButton1.setBackground(new java.awt.Color(0, 102, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Làm mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(247, 247, 247));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));
        jPanel4.setPreferredSize(new java.awt.Dimension(202, 94));

        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Tổng Nguyên Liệu");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtcount.setEditable(false);
        txtcount.setBackground(new java.awt.Color(247, 247, 247));
        txtcount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtcount.setForeground(new java.awt.Color(0, 51, 153));
        txtcount.setText("43");
        txtcount.setBorder(null);
        txtcount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcountActionPerformed(evt);
            }
        });

        btncount.setBackground(new java.awt.Color(247, 247, 247));
        btncount.setBorder(null);
        btncount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtcount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btncount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtcount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btncount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(247, 247, 247));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));

        txtSapHet.setEditable(false);
        txtSapHet.setBackground(new java.awt.Color(247, 247, 247));
        txtSapHet.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtSapHet.setForeground(new java.awt.Color(255, 153, 51));
        txtSapHet.setText("1");
        txtSapHet.setBorder(null);
        txtSapHet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSapHetActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Nguyên Liệu Sắp Hết");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButton3.setBackground(new java.awt.Color(247, 247, 247));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtSapHet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(txtSapHet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(247, 247, 247));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153)));
        jPanel7.setPreferredSize(new java.awt.Dimension(221, 94));

        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Hết Hàng");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtHetHang.setEditable(false);
        txtHetHang.setBackground(new java.awt.Color(247, 247, 247));
        txtHetHang.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtHetHang.setForeground(new java.awt.Color(255, 153, 153));
        txtHetHang.setText("1");
        txtHetHang.setBorder(null);
        txtHetHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHetHangActionPerformed(evt);
            }
        });

        btnHetHang.setBackground(new java.awt.Color(247, 247, 247));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtHetHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnHetHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(txtHetHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnHetHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(247, 247, 247));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));

        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Tổng Giá Trị");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(247, 247, 247));
        txtTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(0, 102, 51));
        txtTotal.setText("24,520,000 VNĐ");
        txtTotal.setBorder(null);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/search-40.png"))); // NOI18N
        btnSearch.setBorder(null);
        btnSearch.setBorderPainted(false);
        btnSearch.setContentAreaFilled(false);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setFocusPainted(false);
        btnSearch.setFocusable(false);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jHeaderLayout = new javax.swing.GroupLayout(jHeader);
        jHeader.setLayout(jHeaderLayout);
        jHeaderLayout.setHorizontalGroup(
            jHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHeaderLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(ipSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addGap(16, 16, 16))
            .addGroup(jHeaderLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 154, Short.MAX_VALUE))
        );
        jHeaderLayout.setVerticalGroup(
            jHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHeaderLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHeaderLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSearch)
                        .addGroup(jHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ipSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChiTietNguyenLieu, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
                    .addComponent(jHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1213, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChiTietNguyenLieu, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
        // ==================== Helper Methods ====================

       // Initialize table model
    private void initTable() {
        materialTableModel = (DefaultTableModel) jTable1.getModel();
        jTable1.setRowHeight(30);

        DefaultTableCellRenderer stockRenderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                if (!isSelected && (column == 3 || column == 6)) {
                    Object statusObj = table.getValueAt(row, 6);
                    if (statusObj != null) {
                        String status = statusObj.toString().toUpperCase();
                        if (status.contains("HẾT HÀNG")) {
                            c.setForeground(DANGER_COLOR);
                        } else if (status.contains("SẮP HẾT")) {
                            c.setForeground(WARNING_COLOR);
                        } else {
                            c.setForeground(Color.BLACK);
                        }
                    }
                } else if (!isSelected) {
                    c.setForeground(Color.BLACK);
                }
                return c;
            }
        };

        jTable1.getColumnModel().getColumn(3).setCellRenderer(stockRenderer);
        jTable1.getColumnModel().getColumn(6).setCellRenderer(stockRenderer);
    }

    // Setup selection listener to show material details
    private void setupTableSelection() {
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int row = jTable1.getSelectedRow();
                    if (row >= 0 && row < materials.size()) {
                        selectedMaterial = materials.get(row);
                        showMaterialDetails(selectedMaterial);
                    }
                }
            }
        });
    }
    // Make statistic text fields transparent
    private void styleSummaryTextFields() {
        Color transparent = new Color(0, 0, 0, 0);
        txtcount.setBackground(transparent);
        txtcount.setOpaque(false);
        txtSapHet.setBackground(transparent);
        txtSapHet.setOpaque(false);
        txtHetHang.setBackground(transparent);
        txtHetHang.setOpaque(false);
    }
    
    // Load all materials and update counts
    private void loadAllMaterials() {
        materials = materialService.getAllMaterials();
        refreshTable(materials);
        updateCounts();
    }

    // Refresh table data
    private void refreshTable(List<Material> list) {
        materialTableModel.setRowCount(0);
        for (Material m : list) {
            materialTableModel.addRow(new Object[]{
                m.getId(),
                m.getName(),
                m.getUnit(),
                m.getQuantity(),
                m.getPricePerUnit(),
                m.getThreshold(),
                m.getStockStatus()
            });
        }
        if (!list.isEmpty()) {
            jTable1.setRowSelectionInterval(0, 0);
            selectedMaterial = list.get(0);
            showMaterialDetails(selectedMaterial);
        } else {
            selectedMaterial = null;
            showMaterialDetails(null);
        }
    }

    // Update statistic fields
    private void updateCounts() {
        List<Material> all = materialService.getAllMaterials();
        txtcount.setText(String.valueOf(all.size()));
        txtSapHet.setText(String.valueOf(materialService.getLowStockMaterials().size()));
        txtHetHang.setText(String.valueOf(materialService.getOutOfStockMaterials().size()));

        BigDecimal totalValue = BigDecimal.ZERO;
        for (Material m : all) {
            totalValue = totalValue.add(m.getTotalValue());
        }
        txtTotal.setText(formatCurrency(totalValue));
    }

    // Search materials by keyword
    private void searchMaterials() {
        String keyword = ipSearch.getText().trim();
        if (keyword.isEmpty()) {
            loadAllMaterials();
        } else {
            List<Material> result = materialService.searchMaterials(keyword);
            refreshTable(result);
        }
    }

    // Reset search and show all materials
    private void resetTable() {
        ipSearch.setText("");
        loadAllMaterials();
    }

    // Show low stock materials
    private void showLowStockMaterials() {
        List<Material> low = materialService.getLowStockMaterials();
        refreshTable(low);
    }

    // Show out of stock materials
    private void showOutOfStockMaterials() {
        List<Material> out = materialService.getOutOfStockMaterials();
        refreshTable(out);
    }

    // Display material details on right panel
    private void showMaterialDetails(Material m) {
        if (m == null) {
            txtName.setText("");
            txtID.setText("ID:");
            txtQty.setText("Số lượng:");
            txtThread.setText("Ngưỡng tối thiểu:");
            txtValue.setText("Giá trị:");
            return;
        }
        txtName.setText(m.getName());
        txtID.setText("ID: " + m.getId());
        txtQty.setText("Số lượng: " + m.getQuantity() + " " + m.getUnit());
        txtThread.setText("Ngưỡng tối thiểu: " + m.getThreshold());
        txtValue.setText("Giá trị: " + formatCurrency(m.getTotalValue()));
    }

    // Open dialog to create material
    private void openCreateMaterialDialog() {
        Frame frame = (Frame) SwingUtilities.getWindowAncestor(this);
        ThemNguyenLieuDialog dialog = new ThemNguyenLieuDialog(frame);
        dialog.setLocationRelativeTo(frame);
        dialog.setVisible(true);
        loadAllMaterials();
    }

    // Open dialog to edit selected material
    private void openEditMaterialDialog() {
        if (selectedMaterial == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nguyên liệu");
            return;
        }
        Frame frame = (Frame) SwingUtilities.getWindowAncestor(this);
        SuaNguyenLieuDialog dialog = new SuaNguyenLieuDialog(frame, selectedMaterial);
        dialog.setLocationRelativeTo(frame);
        dialog.setVisible(true);
        loadAllMaterials();
    }

    // Delete selected material
    private void deleteSelectedMaterial() {
        if (selectedMaterial == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nguyên liệu");
            return;
        }
        if (materialController.delete(selectedMaterial.getId())) {
            loadAllMaterials();
        }
    }

    // Format currency to VNĐ
    private String formatCurrency(BigDecimal value) {
        NumberFormat format = NumberFormat.getInstance();
        return format.format(value) + " VNĐ";
    }

    
    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    private void txtThreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThreadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThreadActionPerformed

    private void txtValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValueActionPerformed

    private void ipSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ipSearchKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            searchMaterials();
        }
    }//GEN-LAST:event_ipSearchKeyPressed

    private void ipSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipSearchActionPerformed
        searchMaterials();
    }//GEN-LAST:event_ipSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        resetTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcountActionPerformed

    private void txtHetHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHetHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHetHangActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnNhapKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhapKhoMouseClicked
        // TODO add your handling code here:
        btnNhapKhoActionPerformed(null);
    }//GEN-LAST:event_btnNhapKhoMouseClicked

    private void btnNhapKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapKhoActionPerformed
        javax.swing.JFrame frame = (javax.swing.JFrame) SwingUtilities.getWindowAncestor(this);
        NhapKhoDialog dialog = new NhapKhoDialog(frame);
        dialog.setLocationRelativeTo(frame);
        dialog.setVisible(true);

        // Refresh dữ liệu nguyên liệu
        loadAllMaterials();

        // Nếu có thay đổi dữ liệu, refresh tất cả history panels
        if (dialog.isDataChanged()) {
            refreshAllHistoryPanels();
        } 
    }//GEN-LAST:event_btnNhapKhoActionPerformed

    private void btnRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecordMouseClicked
        // TODO add your handling code here:
        btnRecordActionPerformed(null);
    }//GEN-LAST:event_btnRecordMouseClicked

    private void btnRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordActionPerformed
   // TODO add your handling code here:
        if (historyFrame == null || !historyFrame.isDisplayable()) {
            // Tạo mới historyPanel và historyFrame
            historyPanel = new LichSuKhoPanel();
            historyFrame = new javax.swing.JFrame("Lịch Sử Xuất/Nhập Kho");
            historyFrame.setContentPane(historyPanel);
            historyFrame.pack();
            historyFrame.setLocationRelativeTo(this);

            // Thêm WindowListener để cleanup khi đóng
            historyFrame.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    historyPanel = null;
                    historyFrame = null;
                }
            });
        } else {
            // Nếu frame đã tồn tại, refresh dữ liệu
            if (historyPanel != null) {
                historyPanel.refreshData();
            }
        }

        // Hiển thị frame
        historyFrame.setVisible(true);
        historyFrame.toFront();
        historyFrame.requestFocus();
    }//GEN-LAST:event_btnRecordActionPerformed

    private void btncountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncountActionPerformed
        // TODO add your handling code here:
        loadAllMaterials();
    }//GEN-LAST:event_btncountActionPerformed

    private void txtSapHetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSapHetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSapHetActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnXuatKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatKhoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXuatKhoMouseClicked

    private void btnXuatKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatKhoActionPerformed
        // TODO add your handling code here:
        if (selectedMaterial == null) {
            JOptionPane.showMessageDialog(this, 
                "Vui lòng chọn nguyên liệu cần xuất/điều chỉnh!");
            return;
        }

        javax.swing.JFrame frame = (javax.swing.JFrame) SwingUtilities.getWindowAncestor(this);
        XuatKhoDialog dialog = new XuatKhoDialog(frame, selectedMaterial);
        dialog.setLocationRelativeTo(frame);
        dialog.setVisible(true);

        // Refresh dữ liệu nguyên liệu
        loadAllMaterials();

        // Nếu có thay đổi dữ liệu, refresh tất cả history panels
        if (dialog.isDataChanged()) {
            refreshAllHistoryPanels();
        }
    }//GEN-LAST:event_btnXuatKhoActionPerformed

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        searchMaterials();
    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        searchMaterials();
    }//GEN-LAST:event_btnSearchActionPerformed
    

    private void refreshAllHistoryPanels() {
        // Refresh historyPanel nội bộ
        if (historyPanel != null) {
            historyPanel.refreshData();
        }

        // Refresh historyFrame nếu đang mở
        if (historyFrame != null && historyFrame.isDisplayable() && historyFrame.isVisible()) {
            Component contentPane = historyFrame.getContentPane();
            if (contentPane instanceof LichSuKhoPanel) {
                ((LichSuKhoPanel) contentPane).refreshData();
            }
        }

        // Refresh any other registered history panels
        LichSuKhoPanel.LichSuKhoPanelManager.refreshAllPanels();
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChiTietNguyenLieu;
    private javax.swing.JButton btnHetHang;
    private javax.swing.JButton btnNhapKho;
    private javax.swing.JButton btnRecord;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnXuatKho;
    private javax.swing.JButton btncount;
    private javax.swing.JTextField ipSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jHeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtHetHang;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtSapHet;
    private javax.swing.JTextField txtThread;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtValue;
    private javax.swing.JTextField txtcount;
    // End of variables declaration//GEN-END:variables
}
