/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlyquanan.view.userProfile;
import com.mycompany.quanlyquanan.model.Employee;
import com.mycompany.quanlyquanan.utils.Session;
import com.mycompany.quanlyquanan.view.Employee.EditEmployeeDialog;
import com.mycompany.quanlyquanan.view.LoginFrame;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
/**
 *
 * @author Admin
 */
public class UserProfilePanel extends javax.swing.JPanel {
    Employee currentUser ;
    /**
     * Creates new form UserProfilePanel
     */
    public UserProfilePanel() {
        initComponents();
        setSelectedEmp(Session.getInstance().getCurrentUser());

    }

    public void setSelectedEmp(Employee selectedEmp) {
        System.out.println("Setting selected employee: " + selectedEmp);
        this.currentUser = selectedEmp;
        if (selectedEmp == null) {
            ipId.setText("");
            ipName.setText("");
            ipUserName.setText("");
            ipPosition.setText("");
            ipRole.setText("");
            ipPhone.setText("");
            ipAdd.setText("");
            ipEmail.setText("");
            // TODO: Clear avatar image if needed
            return;
        }
        ipId.setText(String.valueOf(selectedEmp.getId()));
        ipName.setText(selectedEmp.getName());
        ipUserName.setText(selectedEmp.getUsername());
        ipPosition.setText(selectedEmp.getPosition());
        ipRole.setText(selectedEmp.getRole());
        ipPhone.setText(selectedEmp.getPhone());
        ipAdd.setText(selectedEmp.getAddress());
        ipEmail.setText(selectedEmp.getEmail());
        
        
        // Hiển thị ảnh
        if (selectedEmp.getAvatar() != null && !selectedEmp.getAvatar().isEmpty()) {
            ImageIcon icon = new ImageIcon(selectedEmp.getAvatar());
            Image img = icon.getImage().getScaledInstance(160, 160, Image.SCALE_SMOOTH);
            ipAvatar.setIcon(new ImageIcon(img));
        } else {
            ImageIcon icon = new ImageIcon("assets/images/employee/default.png");
            Image img = icon.getImage().getScaledInstance(160, 160, Image.SCALE_SMOOTH);
            ipAvatar.setIcon(new ImageIcon(img));

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnProfile = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ipAvatar = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ipUserName = new javax.swing.JLabel();
        ipName = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ipPosition = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ipRole = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        ipPhone = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ipAdd = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ipEmail = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ipId = new javax.swing.JLabel();
        toolNav = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnChangePass = new javax.swing.JButton();

        setBackground(new java.awt.Color(244, 244, 244));

        pnProfile.setBackground(new java.awt.Color(255, 255, 255));
        pnProfile.setMinimumSize(new java.awt.Dimension(351, 448));
        pnProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Ảnh");
        pnProfile.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        ipAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/employee/coala-160.png"))); // NOI18N
        pnProfile.add(ipAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 163, 175));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("User name:");
        pnProfile.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        ipUserName.setText("01");
        pnProfile.add(ipUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, -1));

        ipName.setText("nguyẽn văn thị Ngàn");
        pnProfile.add(ipName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Họ tên:");
        pnProfile.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Vị trí:");
        pnProfile.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        ipPosition.setText("Nhân viên");
        pnProfile.add(ipPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Role:");
        pnProfile.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        ipRole.setText("Nhân viên");
        pnProfile.add(ipRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 242, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Điện thoại: ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 15, -1, -1));

        ipPhone.setText("0123456789");
        jPanel1.add(ipPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 15, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Địa chỉ:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 46, -1, -1));

        ipAdd.setText("HCM");
        jPanel1.add(ipAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 46, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Email:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 77, -1, -1));

        ipEmail.setText("ádsadsadasdasdsadsa");
        jPanel1.add(ipEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 77, -1, -1));

        pnProfile.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 310, 110));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("ID:");
        pnProfile.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        ipId.setText("01");
        pnProfile.add(ipId, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        toolNav.setBackground(new java.awt.Color(255, 255, 255));
        toolNav.setPreferredSize(new java.awt.Dimension(1275, 100));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel2.setText("User Profile");
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 22));

        btnEdit.setBackground(new java.awt.Color(255, 242, 242));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/pencil-40.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setBorder(null);
        btnEdit.setBorderPainted(false);
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setOpaque(true);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(244, 244, 244));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/Logout.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setOpaque(true);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnChangePass.setBackground(new java.awt.Color(244, 244, 244));
        btnChangePass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/Password.png"))); // NOI18N
        btnChangePass.setText("Change Pass");
        btnChangePass.setBorder(null);
        btnChangePass.setBorderPainted(false);
        btnChangePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangePass.setFocusable(false);
        btnChangePass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChangePass.setOpaque(true);
        btnChangePass.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChangePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChangePassMouseClicked(evt);
            }
        });
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toolNavLayout = new javax.swing.GroupLayout(toolNav);
        toolNav.setLayout(toolNavLayout);
        toolNavLayout.setHorizontalGroup(
            toolNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolNavLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(760, Short.MAX_VALUE))
        );
        toolNavLayout.setVerticalGroup(
            toolNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolNavLayout.createSequentialGroup()
                .addGroup(toolNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(toolNavLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(toolNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(toolNavLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(pnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(toolNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
      
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        EditUserDialog editEDialog = new EditUserDialog(parentFrame, true, this, currentUser);
        editEDialog.setLocationRelativeTo(parentFrame);
        editEDialog.setVisible(true);
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked


        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this,
            "Bạn có chắc muốn đăng xuất?",
            "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            Session.getInstance().setCurrentUser(null);
            JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            parentFrame.dispose();
            LoginFrame loginFrame = new LoginFrame();
            loginFrame.setLocationRelativeTo(null);
            loginFrame.setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnChangePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePassMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangePassMouseClicked

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
         JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        ChangePassDialog changePassDialog = new ChangePassDialog(parentFrame, true);
        changePassDialog.setLocationRelativeTo(parentFrame);
        changePassDialog.setVisible(true);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangePassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel ipAdd;
    private javax.swing.JLabel ipAvatar;
    private javax.swing.JLabel ipEmail;
    private javax.swing.JLabel ipId;
    private javax.swing.JLabel ipName;
    private javax.swing.JLabel ipPhone;
    private javax.swing.JLabel ipPosition;
    private javax.swing.JLabel ipRole;
    private javax.swing.JLabel ipUserName;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnProfile;
    private javax.swing.JPanel toolNav;
    // End of variables declaration//GEN-END:variables
}
