/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/OkCancelDialog.java to edit this template
 */
package com.mycompany.quanlyquanan.view.category;

import com.mycompany.quanlyquanan.controller.CategoryController;
import com.mycompany.quanlyquanan.model.Category;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import com.mycompany.quanlyquanan.service.MailerService;
import com.mycompany.quanlyquanan.utils.ComponentStyleUtil;
import com.mycompany.quanlyquanan.utils.HashUtil;
import com.mycompany.quanlyquanan.utils.ImageUtils;
import com.mycompany.quanlyquanan.utils.PasswordGeneratorUtil;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.SwingWorker;
import org.passay.PasswordGenerator;
import org.passay.PasswordUtils;

/**
 *
 * @author Admin
 */
public class CreateCategoryDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateCategoryDialog.class.getName());

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form CreateEmployeeDialog
     */
    private QuanLyDanhMucPanel parentPanel;
    private CategoryController controller;
    private int returnStatus = RET_CANCEL;

    public CreateCategoryDialog(java.awt.Frame parent, boolean modal, QuanLyDanhMucPanel parentPanel) {
        super(parent, modal);
        this.parentPanel = parentPanel;
        this.controller = new CategoryController();
        
        initComponents();
        setupEventHandlers();
        setupFormBehavior();
        
        // Focus on name field
        SwingUtilities.invokeLater(() -> ipName.requestFocus());
        ComponentStyleUtil.styleMainButton(bntAdd);
        ComponentStyleUtil.styleSecondButton(btnCancel);
    }
    
    private void setupEventHandlers() {
        // ESC key to close
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }
    private void setupFormBehavior() {
        // Setup radio buttons
        gMerge.add(ipTrueMerge);
        gMerge.add(ipFalseMerge1);
        
        // Set default values
        ipTrueMerge.setSelected(true); // Active by default
        ipTrueMerge.setText("Có");
        ipFalseMerge1.setText("Không");
        
        // Setup labels
        jLabel19.setText("Mô tả:");
        
        // Allow multiline in description
        ipDescription.setToolTipText("Nhập mô tả cho danh mục (tối đa 500 ký tự)");
        ipName.setToolTipText("Nhập tên danh mục (tối đa 100 ký tự)");
        
        // Set dialog properties
        setTitle("Tạo Danh Mục Mới");
        setLocationRelativeTo(getParent());
        setResizable(false);
    }
    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gMerge = new javax.swing.ButtonGroup();
        pnProfile = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        bntAdd = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        ipName = new javax.swing.JTextField();
        ipDescription = new javax.swing.JTextField();
        ipTrueMerge = new javax.swing.JRadioButton();
        ipFalseMerge1 = new javax.swing.JRadioButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnProfile.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Create Category");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Tên :");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Active :");

        btnCancel.setBackground(new java.awt.Color(255, 51, 51));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Hủy");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        bntAdd.setBackground(new java.awt.Color(0, 153, 0));
        bntAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntAdd.setForeground(new java.awt.Color(255, 255, 255));
        bntAdd.setText("Thêm");
        bntAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntAddMouseClicked(evt);
            }
        });
        bntAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAddActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Mô tả:");

        ipName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipNameActionPerformed(evt);
            }
        });

        ipDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipDescriptionActionPerformed(evt);
            }
        });
        ipDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ipDescriptionKeyTyped(evt);
            }
        });

        gMerge.add(ipTrueMerge);
        ipTrueMerge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ipTrueMerge.setForeground(new java.awt.Color(0, 153, 51));
        ipTrueMerge.setText("True");
        ipTrueMerge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipTrueMergeActionPerformed(evt);
            }
        });

        gMerge.add(ipFalseMerge1);
        ipFalseMerge1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ipFalseMerge1.setForeground(new java.awt.Color(102, 102, 102));
        ipFalseMerge1.setText("False");
        ipFalseMerge1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipFalseMerge1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnProfileLayout = new javax.swing.GroupLayout(pnProfile);
        pnProfile.setLayout(pnProfileLayout);
        pnProfileLayout.setHorizontalGroup(
            pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfileLayout.createSequentialGroup()
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnProfileLayout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(ipTrueMerge)
                                .addGap(38, 38, 38)
                                .addComponent(ipFalseMerge1))
                            .addGroup(pnProfileLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(bntAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnProfileLayout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23)
                                .addGroup(pnProfileLayout.createSequentialGroup()
                                    .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel17))
                                    .addGap(65, 65, 65)
                                    .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ipName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ipDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(2, 2, 2)))
                    .addGroup(pnProfileLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel11)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        pnProfileLayout.setVerticalGroup(
            pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfileLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(ipName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnProfileLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel19))
                    .addGroup(pnProfileLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(ipDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(ipTrueMerge)
                    .addComponent(ipFalseMerge1))
                .addGap(37, 37, 37)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(pnProfile, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void ipDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipDescriptionActionPerformed
        // TODO add your handling code here:
        ipDescription.requestFocus();
    }//GEN-LAST:event_ipDescriptionActionPerformed

    private void ipNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ipNameActionPerformed

    private void bntAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAddActionPerformed
        saveCategory();
    }//GEN-LAST:event_bntAddActionPerformed

    private void bntAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntAddMouseClicked
        saveCategory();
        // TODO add your handling code here:
    }//GEN-LAST:event_bntAddMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        doClose(RET_CANCEL);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        doClose(RET_CANCEL);
    }//GEN-LAST:event_btnCancelMouseClicked

    private void ipDescriptionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ipDescriptionKeyTyped


        // TODO add your handling code here:
    }//GEN-LAST:event_ipDescriptionKeyTyped

    private void ipTrueMergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipTrueMergeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipTrueMergeActionPerformed

    private void ipFalseMerge1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipFalseMerge1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipFalseMerge1ActionPerformed

    private void saveCategory() {
        String name = ipName.getText().trim();
        String description = ipDescription.getText().trim();
        boolean isActive = ipTrueMerge.isSelected();
        
        // Validation
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "❌ Tên danh mục không được để trống!", 
                "Lỗi", JOptionPane.ERROR_MESSAGE);
            ipName.requestFocus();
            return;
        }
        
        if (name.length() > 100) {
            JOptionPane.showMessageDialog(this,
                "❌ Tên danh mục không được quá 100 ký tự!",
                "Lỗi", JOptionPane.ERROR_MESSAGE);
            ipName.requestFocus();
            return;
        }
        
        if (description.length() > 500) {
            JOptionPane.showMessageDialog(this,
                "❌ Mô tả không được quá 500 ký tự!",
                "Lỗi", JOptionPane.ERROR_MESSAGE);
            ipDescription.requestFocus();
            return;
        }

        // Check if category name already exists
        if (controller.isNameExists(name, 0)) {
            JOptionPane.showMessageDialog(this,
                "❌ Tên danh mục đã tồn tại!",
                "Lỗi", JOptionPane.ERROR_MESSAGE);
            ipName.requestFocus();
            return;
        }

        // Create category object
        Category category = new Category();
        category.setName(name);
        category.setDescription(description.isEmpty() ? null : description);
        category.setActive(isActive);

        // Save category
        boolean success = controller.create(category);
        
        if (success) {
            // Refresh parent table
            if (parentPanel != null) {
                parentPanel.loadTableData();
            }
            
            JOptionPane.showMessageDialog(this, 
                "✅ Tạo danh mục thành công!", 
                "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            
            // Ask if user wants to create another category
            int choice = JOptionPane.showConfirmDialog(this,
                "Bạn có muốn tạo thêm danh mục khác?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION);
                
            if (choice == JOptionPane.YES_OPTION) {
                // Clear form for new category
                clearForm();
            } else {
                doClose(RET_OK);
            }
        }
    }
    
    private void clearForm() {
        ipName.setText("");
        ipDescription.setText("");
        ipTrueMerge.setSelected(true);
        ipName.requestFocus();
    }
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.ButtonGroup gMerge;
    private javax.swing.JTextField ipDescription;
    private javax.swing.JRadioButton ipFalseMerge1;
    private javax.swing.JTextField ipName;
    private javax.swing.JRadioButton ipTrueMerge;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel pnProfile;
    // End of variables declaration//GEN-END:variables


}
