/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/OkCancelDialog.java to edit this template
 */
package com.mycompany.quanlyquanan.view.table;

import com.mycompany.quanlyquanan.utils.ComponentStyleUtil;
import com.mycompany.quanlyquanan.view.Employee.*;
import com.mycompany.quanlyquanan.controller.EmployeeController;
import com.mycompany.quanlyquanan.controller.TableController;
import com.mycompany.quanlyquanan.model.Employee;
import com.mycompany.quanlyquanan.model.Table;
import com.mycompany.quanlyquanan.service.MailerService;
import com.mycompany.quanlyquanan.utils.HashUtil;
import com.mycompany.quanlyquanan.utils.ImageUtils;
import com.mycompany.quanlyquanan.utils.PasswordGeneratorUtil;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.SwingWorker;
import org.passay.PasswordGenerator;
import org.passay.PasswordUtils;

/**
 *
 * @author Admin
 */
public class EditTableDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditTableDialog.class.getName());

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form CreateEmployeeDialog
     */
    private QuanLyBanPanel parentPanel;
    private TableController controller = new TableController();
    private Table selectedTable;

    public EditTableDialog(java.awt.Frame parent, boolean modal, QuanLyBanPanel parentPanel, Table selectedTable) {
        super(parent, modal);
        initComponents();
        this.parentPanel = parentPanel;
        this.selectedTable = selectedTable;

        ipName.setText(selectedTable.getName());
        ipCapacity.setText(String.valueOf(selectedTable.getCapacity()));
        ipGroup.setText(selectedTable.getLocationGroup());

        if (selectedTable.isCanMerge()) {
            ipTrueMerge.setSelected(true);
        } else {
            ipFalseMerge1.setSelected(true);
        }

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });

        ComponentStyleUtil.styleMainButton(bntAdd);
        ComponentStyleUtil.styleSecondButton(btnCancel);
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gMerge = new javax.swing.ButtonGroup();
        pnProfile = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        bntAdd = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        ipName = new javax.swing.JTextField();
        ipCapacity = new javax.swing.JTextField();
        ipTrueMerge = new javax.swing.JRadioButton();
        ipFalseMerge1 = new javax.swing.JRadioButton();
        ipGroup = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnProfile.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Edit Table");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Tên bàn :");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Can merge :");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Group location :");

        btnCancel.setBackground(new java.awt.Color(255, 51, 51));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Hủy");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        bntAdd.setBackground(new java.awt.Color(0, 153, 0));
        bntAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntAdd.setForeground(new java.awt.Color(255, 255, 255));
        bntAdd.setText("Sửa");
        bntAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntAddMouseClicked(evt);
            }
        });
        bntAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAddActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Sức chứa :");

        ipName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipNameActionPerformed(evt);
            }
        });

        ipCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipCapacityActionPerformed(evt);
            }
        });
        ipCapacity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ipCapacityKeyTyped(evt);
            }
        });

        gMerge.add(ipTrueMerge);
        ipTrueMerge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ipTrueMerge.setForeground(new java.awt.Color(0, 153, 51));
        ipTrueMerge.setText("True");
        ipTrueMerge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipTrueMergeActionPerformed(evt);
            }
        });

        gMerge.add(ipFalseMerge1);
        ipFalseMerge1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ipFalseMerge1.setForeground(new java.awt.Color(102, 102, 102));
        ipFalseMerge1.setText("False");
        ipFalseMerge1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipFalseMerge1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnProfileLayout = new javax.swing.GroupLayout(pnProfile);
        pnProfile.setLayout(pnProfileLayout);
        pnProfileLayout.setHorizontalGroup(
            pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfileLayout.createSequentialGroup()
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnProfileLayout.createSequentialGroup()
                            .addGap(171, 171, 171)
                            .addComponent(ipTrueMerge)
                            .addGap(38, 38, 38)
                            .addComponent(ipFalseMerge1))
                        .addGroup(pnProfileLayout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addComponent(bntAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(103, 103, 103)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnProfileLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(pnProfileLayout.createSequentialGroup()
                                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ipName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ipCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ipGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        pnProfileLayout.setVerticalGroup(
            pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfileLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(ipName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(ipCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(ipGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(ipTrueMerge)
                    .addComponent(ipFalseMerge1))
                .addGap(37, 37, 37)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(pnProfile, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void ipCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipCapacityActionPerformed

    private void ipNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipNameActionPerformed

    private void bntAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAddActionPerformed
        // TODO add your handling code here:
        String name = ipName.getText().trim();
        String capacityStr = ipCapacity.getText().trim();
        boolean canMerge = ipTrueMerge.isSelected();
        String locationGroup = ipGroup.getText().trim();

// Validate
        boolean isChanged =
            !name.equals(selectedTable.getName()) ||
            capacityStr.equals(selectedTable.getCapacity()) ||
            canMerge != selectedTable.isCanMerge() ||
            !locationGroup.equals(selectedTable.getLocationGroup());

    if (!isChanged) {
        JOptionPane.showMessageDialog(this, "Không có thay đổi nào để cập nhật");
        return;
    }


        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên bàn không được để trống");
            return;
        }

        if (capacityStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sức chứa không được để trống");
            return;
        }

        int capacity;
        try {
            capacity = Integer.parseInt(capacityStr);
            if (capacity <= 0) {
                JOptionPane.showMessageDialog(this, "Sức chứa phải lớn hơn 0");
                return;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Sức chứa phải là số nguyên");
            return;
        }

        if (locationGroup.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Khu vực không được để trống");
            return;
        }

// Tạo đối tượng Table
        Table table = selectedTable;
        table.setName(name);
        table.setCapacity(capacity);
        table.setCanMerge(canMerge);
        table.setLocationGroup(locationGroup);

// Gọi controller
        boolean success = controller.updateTable(table);
        if (success) {
            JOptionPane.showMessageDialog(this, "Cập nhật bàn thành công");
            parentPanel.loadTableData();
            dispose(); // đóng dialog
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật bàn");
        }


    }//GEN-LAST:event_bntAddActionPerformed

    private void bntAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntAddMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_bntAddMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void ipCapacityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ipCapacityKeyTyped

        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume(); // chặn ký tự

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_ipCapacityKeyTyped

    private void ipTrueMergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipTrueMergeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipTrueMergeActionPerformed

    private void ipFalseMerge1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipFalseMerge1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipFalseMerge1ActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                CreateEmployeeDialog dialog = new CreateEmployeeDialog(new javax.swing.JFrame(), true,parentPanel);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.ButtonGroup gMerge;
    private javax.swing.JTextField ipCapacity;
    private javax.swing.JRadioButton ipFalseMerge1;
    private javax.swing.JTextField ipGroup;
    private javax.swing.JTextField ipName;
    private javax.swing.JRadioButton ipTrueMerge;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel pnProfile;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
