    package com.mycompany.quanlyquanan.dao;

import com.mycompany.quanlyquanan.model.Material;
import com.mycompany.quanlyquanan.utils.DatabaseConnector;

import java.math.BigDecimal;
import java.sql.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author Admin
 */
public class MaterialDAO {
    
    private final Connection conn;
    private final String tableName;
    //private final boolean hasCategoryColumn;
    //private final boolean hasExpiryDateColumn;

    public MaterialDAO() {
        this.conn = DatabaseConnector.getConnection();
        this.tableName = resolveTableName();
        //this.hasCategoryColumn = checkColumnExists("category");
        //this.hasExpiryDateColumn = checkColumnExists("expiry_date");
        
    }

    private boolean checkColumnExists(String columnName) {
        try {
            DatabaseMetaData meta = conn.getMetaData();
            try (ResultSet rs = meta.getColumns(null, null, tableName, columnName)) {
                return rs.next();
            }
        } catch (SQLException e) {
            System.err.println("Error checking column " + columnName + ": " + e.getMessage());
            return false;
        }
    }

    private String resolveTableName() {
        try {
            DatabaseMetaData meta = conn.getMetaData();
            ResultSet rs = meta.getTables(null, null, "materials", null);
            if (rs.next()) {
                return "materials";
            }
            rs = meta.getTables(null, null, "active_materials", null);
            if (rs.next()) {
                return "active_materials";
            }
        } catch (SQLException e) {
            System.err.println("Error detecting materials table: " + e.getMessage());
        }
        return "materials";
    }

    private String withTableName(String sql) {
        return sql.replace("materials", tableName);
    }

    private PreparedStatement prepareStatement(String sql) throws SQLException {
        return conn.prepareStatement(withTableName(sql));
    }

    private PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return conn.prepareStatement(withTableName(sql), autoGeneratedKeys);
    }

    public List<Material> getAll() {
        List<Material> materials = new ArrayList<>();
        String sql = "SELECT * FROM materials ORDER BY name";
        
        try (PreparedStatement stmt = prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {
            
            while (rs.next()) {
                materials.add(mapResultSet(rs));
            }
        } catch (SQLException e) {
            System.err.println("Error getting all materials: " + e.getMessage());
            e.printStackTrace();
        }
        return materials;
    }

    public List<Material> getAllActive() {
        List<Material> materials = new ArrayList<>();
        String sql;
        if ("materials".equals(tableName)) {
            sql = "SELECT * FROM materials WHERE is_active = 1 ORDER BY name";
        } else {
            sql = "SELECT * FROM " + tableName + " ORDER BY name";
        }
        
        try (PreparedStatement stmt = prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {
            
            while (rs.next()) {
                materials.add(mapResultSet(rs));
            }
        } catch (SQLException e) {
            System.err.println("Error getting active materials: " + e.getMessage());
            e.printStackTrace();
        }
        return materials;
    }

    public List<Material> getLowStockMaterials() {
        List<Material> materials = new ArrayList<>();
        String sql;
        if ("materials".equals(tableName)) {
            sql = "SELECT * FROM materials WHERE quantity <= threshold AND is_active = 1 ORDER BY name";
        } else {
            sql = "SELECT * FROM " + tableName + " WHERE quantity <= threshold ORDER BY name";
        }
        
        try (PreparedStatement stmt = prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {
            
            while (rs.next()) {
                materials.add(mapResultSet(rs));
            }
        } catch (SQLException e) {
            System.err.println("Error getting low stock materials: " + e.getMessage());
            e.printStackTrace();
        }
        return materials;
    }

    public Material getById(int id) {

        String sql = "SELECT * FROM " + tableName + " WHERE id = ?";
        
        try (PreparedStatement stmt = prepareStatement(sql)) {
            stmt.setInt(1, id);
            ResultSet rs = stmt.executeQuery();
            
            if (rs.next()) {
                return mapResultSet(rs);
            }
        } catch (SQLException e) {
            System.err.println("Error getting material by id: " + e.getMessage());
            e.printStackTrace();
        }
        return null;
    }

    public Material getByName(String name) {
        if (name == null || name.trim().isEmpty()) {
            return null;
        }

        String sql = "SELECT * FROM materials WHERE name = ?";

        try (PreparedStatement stmt = prepareStatement(sql)) {
            stmt.setString(1, name.trim());

            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    return mapResultSet(rs);
                }
            }
        } catch (SQLException e) {
            System.err.println("Error getting material by name: " + e.getMessage());
            e.printStackTrace();
        }
        return null;
    }

    public boolean insert(Material material) {
        String sql = """
            INSERT INTO materials (
                name, unit, quantity, price_per_unit, threshold,
                is_active, created_at, updated_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """;

        try (PreparedStatement stmt = prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            int idx = 1;
            stmt.setString(idx++, material.getName());
            stmt.setString(idx++, material.getUnit());
            stmt.setBigDecimal(idx++, material.getQuantity());
            stmt.setBigDecimal(idx++, material.getPricePerUnit());
            stmt.setBigDecimal(idx++, material.getThreshold());
            stmt.setBoolean(idx++, material.isActive());
            //stmt.setString(idx++, material.getDescription());
            stmt.setTimestamp(idx++, Timestamp.valueOf(LocalDateTime.now()));
            stmt.setTimestamp(idx++, Timestamp.valueOf(LocalDateTime.now()));

            int result = stmt.executeUpdate();
            if (result > 0) {
                ResultSet keys = stmt.getGeneratedKeys();
                if (keys.next()) {
                    material.setId(keys.getInt(1));
                }
                return true;
            }
        } catch (SQLException e) {
            System.err.println("Error inserting material: " + e.getMessage());
            e.printStackTrace();
        }
        return false;
    }


    public boolean update(Material material) {
        String sql = """
            UPDATE materials SET
                name = ?, unit = ?, quantity = ?, price_per_unit = ?,
                threshold = ?, is_active = ?,
                updated_at = ?
            WHERE id = ?
            """;

        try (PreparedStatement stmt = prepareStatement(sql)) {
            int idx = 1;
            stmt.setString(idx++, material.getName());              // 1: name
            stmt.setString(idx++, material.getUnit());              // 2: unit  
            stmt.setBigDecimal(idx++, material.getQuantity());      // 3: quantity
            stmt.setBigDecimal(idx++, material.getPricePerUnit());  // 4: price_per_unit
            stmt.setBigDecimal(idx++, material.getThreshold());     // 5: threshold
            stmt.setBoolean(idx++, material.isActive());            // 6: is_active
            //stmt.setString(idx++, material.getDescription());       // 7: description
            stmt.setTimestamp(idx++, Timestamp.valueOf(LocalDateTime.now())); // 8: updated_at
            stmt.setInt(idx++, material.getId());                   // 9: WHERE id = ?

            int result = stmt.executeUpdate();
            return result > 0;

        } catch (SQLException e) {
            System.err.println("Error updating material: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }

    

    public boolean updateQuantity(int materialId, BigDecimal newQuantity) {
        String sql = "UPDATE materials SET quantity = ?, updated_at = ? WHERE id = ?";
        
        try (PreparedStatement stmt = prepareStatement(sql)) {
            stmt.setBigDecimal(1, newQuantity);
            stmt.setTimestamp(2, Timestamp.valueOf(LocalDateTime.now()));
            stmt.setInt(3, materialId);
            
            return stmt.executeUpdate() > 0;
        } catch (SQLException e) {
            System.err.println("Error updating material quantity: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }

    public boolean addQuantity(int materialId, BigDecimal addQuantity) {
        String sql = "UPDATE materials SET quantity = quantity + ?, updated_at = ? WHERE id = ?";
        
        try (PreparedStatement stmt = prepareStatement(sql)) {
            stmt.setBigDecimal(1, addQuantity);
            stmt.setTimestamp(2, Timestamp.valueOf(LocalDateTime.now()));
            stmt.setInt(3, materialId);
            
            return stmt.executeUpdate() > 0;
        } catch (SQLException e) {
            System.err.println("Error adding material quantity: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }

    public boolean subtractQuantity(int materialId, BigDecimal subtractQuantity) {
        String sql = "UPDATE materials SET quantity = quantity - ?, updated_at = ? WHERE id = ? AND quantity >= ?";
        
        try (PreparedStatement stmt = prepareStatement(sql)) {
            stmt.setBigDecimal(1, subtractQuantity);
            stmt.setTimestamp(2, Timestamp.valueOf(LocalDateTime.now()));
            stmt.setInt(3, materialId);
            stmt.setBigDecimal(4, subtractQuantity);
            
            return stmt.executeUpdate() > 0;
        } catch (SQLException e) {
            System.err.println("Error subtracting material quantity: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }

    public boolean delete(int id) {
        // Soft delete - chỉ đánh dấu is_active = false
        String sql = "UPDATE materials SET is_active = 0, updated_at = ? WHERE id = ?";
        
        try (PreparedStatement stmt = prepareStatement(sql)) {
            stmt.setTimestamp(1, Timestamp.valueOf(LocalDateTime.now()));
            stmt.setInt(2, id);
            
            return stmt.executeUpdate() > 0;
        } catch (SQLException e) {
            System.err.println("Error deleting material: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }

    public boolean hardDelete(int id) {
        // Hard delete - xóa hoàn toàn khỏi database
        String sql = "DELETE FROM materials WHERE id = ?";
        
        try (PreparedStatement stmt = prepareStatement(sql)) {
            stmt.setInt(1, id);
            return stmt.executeUpdate() > 0;
        } catch (SQLException e) {
            System.err.println("Error hard deleting material: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }

    public List<Material> search(String keyword) {
        List<Material> materials = new ArrayList<>();
        String sql = """
            SELECT * FROM materials 
            WHERE (name LIKE ? OR unit LIKE ?) AND is_active = 1 
            ORDER BY name
            """;

        try (PreparedStatement stmt = prepareStatement(sql)) {
            String searchPattern = "%" + keyword + "%";
            stmt.setString(1, searchPattern);
            stmt.setString(2, searchPattern);
            //stmt.setString(3, searchPattern);
            
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                materials.add(mapResultSet(rs));
            }
        } catch (SQLException e) {
            System.err.println("Error searching materials: " + e.getMessage());
            e.printStackTrace();
        }
        return materials;
    }

    public boolean isNameExists(String name, int excludeId) {
        if (name == null || name.trim().isEmpty()) {
            return false;
        }

        String sql = "SELECT COUNT(*) FROM materials WHERE LOWER(TRIM(name)) = LOWER(TRIM(?)) AND id != ? AND is_active = 1";

        try (PreparedStatement stmt = prepareStatement(sql)) {
            stmt.setString(1, name.trim());
            stmt.setInt(2, excludeId);

            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt(1) > 0;
                }
            }
        } catch (SQLException e) {
            System.err.println("Error checking material name existence: " + e.getMessage());
            e.printStackTrace();
            // Trả về false để không block việc tạo/update
            // Service layer sẽ handle exception này
            return false;
        }
        return false;
    }

    public boolean hasActiveRecipes(int materialId) {
        String sql = """
            SELECT COUNT(*) FROM recipes r
            JOIN dishes d ON r.dish_id = d.id
            WHERE r.material_id = ? AND d.is_available = 1
            """;

        try (PreparedStatement stmt = prepareStatement(sql)) {
            stmt.setInt(1, materialId);
            
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                return rs.getInt(1) > 0;
            }
        } catch (SQLException e) {
            System.err.println("Error checking active recipes: " + e.getMessage());
            e.printStackTrace();
        }
        return false;
    }

    public BigDecimal getTotalInventoryValue() {
        String sql = "SELECT SUM(quantity * price_per_unit) as total_value FROM materials WHERE is_active = 1";

        try (PreparedStatement stmt = prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {
            
            if (rs.next()) {
                BigDecimal totalValue = rs.getBigDecimal("total_value");
                return totalValue != null ? totalValue : BigDecimal.ZERO;
            }
        } catch (SQLException e) {
            System.err.println("Error getting total inventory value: " + e.getMessage());
            e.printStackTrace();
        }
        return BigDecimal.ZERO;
    }

    public List<Material> getMaterialsForDish(int dishId) {
        List<Material> materials = new ArrayList<>();
        String sql = """
            SELECT DISTINCT m.* FROM materials m
            JOIN recipes r ON m.id = r.material_id
            WHERE r.dish_id = ? AND m.is_active = 1
            ORDER BY m.name
            """;

        try (PreparedStatement stmt = prepareStatement(sql)) {
            stmt.setInt(1, dishId);
            ResultSet rs = stmt.executeQuery();
            
            while (rs.next()) {
                materials.add(mapResultSet(rs));
            }
        } catch (SQLException e) {
            System.err.println("Error getting materials for dish: " + e.getMessage());
            e.printStackTrace();
        }
        return materials;
    }
    
    /**
    * Đếm số nguyên liệu đã hết hàng
    */
    public long countOutOfStock() {
        String sql = "SELECT COUNT(*) FROM materials WHERE quantity <= 0 AND is_active = 1";

        try (PreparedStatement stmt = prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            if (rs.next()) {
                return rs.getLong(1);
            }
        } catch (SQLException e) {
            System.err.println("Error counting out of stock materials: " + e.getMessage());
            e.printStackTrace();
        }
        return 0;
    }

    /**
     * Đếm số nguyên liệu đang hoạt động
     */
    public long countActive() {
        String sql = "SELECT COUNT(*) FROM materials WHERE is_active = 1";

        try (PreparedStatement stmt = prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            if (rs.next()) {
                return rs.getLong(1);
            }
        } catch (SQLException e) {
            System.err.println("Error counting active materials: " + e.getMessage());
            e.printStackTrace();
        }
        return 0;
    }

    /**
     * Cập nhật giá đơn vị
     */
    public boolean updateUnitPrice(int materialId, BigDecimal unitPrice) {
        String sql = "UPDATE materials SET price_per_unit = ?, updated_at = ? WHERE id = ?";

        try (PreparedStatement stmt = prepareStatement(sql)) {
            stmt.setBigDecimal(1, unitPrice);
            stmt.setTimestamp(2, Timestamp.valueOf(LocalDateTime.now()));
            stmt.setInt(3, materialId);

            return stmt.executeUpdate() > 0;
        } catch (SQLException e) {
            System.err.println("Error updating unit price: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }

    /**
     * Lấy danh sách nguyên liệu hết hàng
     */
    public List<Material> getOutOfStockMaterials() {
        List<Material> materials = new ArrayList<>();
        String sql = """
            SELECT * FROM materials 
            WHERE quantity <= 0 AND is_active = 1 
            ORDER BY name
            """;

        try (PreparedStatement stmt = prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                materials.add(mapResultSet(rs));
            }
        } catch (SQLException e) {
            System.err.println("Error getting out of stock materials: " + e.getMessage());
            e.printStackTrace();
        }
        return materials;
    }

    /*
    
    public List<Material> getByCategory(String category) {
        List<Material> materials = new ArrayList<>();
        String sql = """
            SELECT * FROM materials 
            WHERE category = ? AND is_active = 1 
            ORDER BY name
            """;

        try (PreparedStatement stmt = prepareStatement(sql)) {
            stmt.setString(1, category);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                materials.add(mapResultSet(rs));
            }
        } catch (SQLException e) {
            System.err.println("Error getting materials by category: " + e.getMessage());
            e.printStackTrace();
        }
        return materials;
    }

    public List<String> getAllCategories() {
        List<String> categories = new ArrayList<>();
        String sql = """
            SELECT DISTINCT category FROM materials 
            WHERE category IS NOT NULL AND category != '' 
            ORDER BY category
            """;
                     
        try (PreparedStatement stmt = prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                categories.add(rs.getString("category"));
            }
        } catch (SQLException e) {
            System.err.println("Error getting categories: " + e.getMessage());
            e.printStackTrace();
        }
        return categories;
    }
    */
    /**
     * Tìm kiếm nguyên liệu theo nhiều tiêu chí
     */
    public List<Material> searchMaterials(String keyword, /*String category,*/ Boolean isActive) {
        List<Material> materials = new ArrayList<>();
        StringBuilder sql = new StringBuilder("""
            SELECT * FROM materials 
            WHERE 1=1
            """);
        List<Object> params = new ArrayList<>();

        if (keyword != null && !keyword.trim().isEmpty()) {
            sql.append(" AND (name LIKE )");
            String searchPattern = "%" + keyword + "%";
            params.add(searchPattern);
            params.add(searchPattern);
        }
        /*
        if (category != null && !category.trim().isEmpty()) {
            sql.append(" AND category = ?");
            params.add(category);
        }
        */
        if (isActive != null) {
            sql.append(" AND is_active = ?");
            params.add(isActive);
        }

        sql.append(" ORDER BY name");

        try (PreparedStatement stmt = prepareStatement(sql.toString())) {
            for (int i = 0; i < params.size(); i++) {
                stmt.setObject(i + 1, params.get(i));
            }

            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                materials.add(mapResultSet(rs));
            }
        } catch (SQLException e) {
            System.err.println("Error searching materials: " + e.getMessage());
            e.printStackTrace();
        }
        return materials;
    }

    /**
     * Lấy top nguyên liệu theo giá trị tồn kho
     */
    public List<Material> getTopMaterialsByValue(int limit) {
        List<Material> materials = new ArrayList<>();
        String sql = """
            SELECT *, (quantity * price_per_unit) as total_value 
            FROM materials 
            WHERE is_active = 1 
            ORDER BY total_value DESC 
            LIMIT ?
            """;

        try (PreparedStatement stmt = prepareStatement(sql)) {
            stmt.setInt(1, limit);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                materials.add(mapResultSet(rs));
            }
        } catch (SQLException e) {
            System.err.println("Error getting top materials by value: " + e.getMessage());
            e.printStackTrace();
        }
        return materials;
    }

    /**
     * Lấy nguyên liệu sắp hết hạn
     */
    /*
    public List<Material> getExpiringMaterials(int daysAhead) {
        List<Material> materials = new ArrayList<>();
        if (!hasExpiryDateColumn) {
            return materials;
        }        
        String sql = """
            SELECT * FROM materials
            WHERE is_active = 1
            AND expiry_date IS NOT NULL
            AND expiry_date <= DATE_ADD(CURDATE(), INTERVAL ? DAY)
            AND expiry_date >= CURDATE()
            ORDER BY expiry_date
            """;


        try (PreparedStatement stmt = prepareStatement(sql)) {
            stmt.setInt(1, daysAhead);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                materials.add(mapResultSet(rs));
            }
        } catch (SQLException e) {
            System.err.println("Error getting expiring materials: " + e.getMessage());
            e.printStackTrace();
        }
        return materials;
    }
    */

    /*

    public Map<String, Map<String, Object>> getInventoryStatsByCategory() {
        Map<String, Map<String, Object>> stats = new HashMap<>();
        String sql = """
            SELECT 
                category,
                COUNT(*) as material_count,
                SUM(quantity * price_per_unit) as total_value,
                SUM(CASE WHEN quantity <= threshold THEN 1 ELSE 0 END) as low_stock_count,
                SUM(CASE WHEN quantity <= 0 THEN 1 ELSE 0 END) as out_of_stock_count
            FROM materials 
            WHERE is_active = 1 
            GROUP BY category
            ORDER BY total_value DESC
            """;

        try (PreparedStatement stmt = prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                String category = rs.getString("category");
                if (category == null) category = "Không phân loại";

                Map<String, Object> categoryStat = new HashMap<>();
                categoryStat.put("material_count", rs.getInt("material_count"));
                categoryStat.put("total_value", rs.getBigDecimal("total_value"));
                categoryStat.put("low_stock_count", rs.getInt("low_stock_count"));
                categoryStat.put("out_of_stock_count", rs.getInt("out_of_stock_count"));

                stats.put(category, categoryStat);
            }
        } catch (SQLException e) {
            System.err.println("Error getting inventory stats by category: " + e.getMessage());
            e.printStackTrace();
        }
        return stats;
    }


    public boolean updateCategoryBatch(List<Integer> materialIds, String newCategory) {
        if (materialIds == null || materialIds.isEmpty()) {
            return false;
        }

        StringBuilder sql = new StringBuilder("UPDATE materials SET category = ?, updated_at = ? WHERE id IN (");
        for (int i = 0; i < materialIds.size(); i++) {
            sql.append("?");
            if (i < materialIds.size() - 1) {
                sql.append(",");
            }
        }
        sql.append(")");

        try (PreparedStatement stmt = prepareStatement(sql.toString())) {
            stmt.setString(1, newCategory);
            stmt.setTimestamp(2, Timestamp.valueOf(LocalDateTime.now()));

            for (int i = 0; i < materialIds.size(); i++) {
                stmt.setInt(i + 3, materialIds.get(i));
            }

            return stmt.executeUpdate() > 0;
        } catch (SQLException e) {
            System.err.println("Error updating category batch: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }
    */
    private void setStatementParameters(PreparedStatement stmt, Material material) throws SQLException {
        stmt.setString(1, material.getName());
        stmt.setString(2, material.getUnit());
        stmt.setBigDecimal(3, material.getPricePerUnit());
        stmt.setBigDecimal(4, material.getQuantity());
        stmt.setBigDecimal(5, material.getThreshold());
        //stmt.setString(6, material.getDescription());
        stmt.setBoolean(7, material.isActive());
    }

    private Material mapResultSet(ResultSet rs) throws SQLException {
        Material material = new Material();

        ResultSetMetaData meta = rs.getMetaData();
        int columnCount = meta.getColumnCount();
        java.util.Set<String> columns = new java.util.HashSet<>();
        for (int i = 1; i <= columnCount; i++) {
            columns.add(meta.getColumnLabel(i).toLowerCase());
        }

        if (columns.contains("id")) material.setId(rs.getInt("id"));
        if (columns.contains("name")) material.setName(rs.getString("name"));
        if (columns.contains("unit")) material.setUnit(rs.getString("unit"));
        if (columns.contains("quantity")) material.setQuantity(rs.getBigDecimal("quantity"));
        if (columns.contains("price_per_unit")) material.setPricePerUnit(rs.getBigDecimal("price_per_unit"));
        if (columns.contains("threshold")) material.setThreshold(rs.getBigDecimal("threshold"));
        if (columns.contains("is_active")) material.setActive(rs.getBoolean("is_active"));
        //if (columns.contains("description")) material.setDescription(rs.getString("description"));

        // BỎ các trường không tồn tại trong database:
        // - supplier (không có trong schema)
        // - created_by, updated_by (không có trong schema)
        // - expiry_date (không có trong schema)

        if (columns.contains("created_at")) {
            Timestamp createdAt = rs.getTimestamp("created_at");
            if (createdAt != null) {
                material.setCreatedAt(createdAt.toLocalDateTime());
            }
        }

        if (columns.contains("updated_at")) {
            Timestamp updatedAt = rs.getTimestamp("updated_at");
            if (updatedAt != null) {
                material.setUpdatedAt(updatedAt.toLocalDateTime());
            }
        }

        return material;
    }

    public boolean hasEnoughQuantity(int materialId, BigDecimal quantity) {
        String sql = "SELECT 1 FROM materials WHERE id = ? AND quantity >= ?";

        try (PreparedStatement stmt = prepareStatement(sql)) {
            stmt.setInt(1, materialId);
            stmt.setBigDecimal(2, quantity);

            try (ResultSet rs = stmt.executeQuery()) {
                return rs.next();
            }
        } catch (SQLException e) {
            System.err.println("Error checking material quantity: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }

    public boolean updateThreshold(int materialId, BigDecimal newThreshold) {
        String sql = "UPDATE materials SET threshold = ?, updated_at = ? WHERE id = ?";

        try (PreparedStatement stmt = prepareStatement(sql)) {
            stmt.setBigDecimal(1, newThreshold);
            stmt.setTimestamp(2, Timestamp.valueOf(LocalDateTime.now()));
            stmt.setInt(3, materialId);

            return stmt.executeUpdate() > 0;
        } catch (SQLException e) {
            System.err.println("Error updating material threshold: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }

    public long count() {
        String sql;
        if ("materials".equals(tableName)) {
            sql = "SELECT COUNT(*) FROM materials WHERE is_active = 1";
        } else {
            sql = "SELECT COUNT(*) FROM " + tableName;
        }

        try (PreparedStatement stmt = prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            if (rs.next()) {
                return rs.getLong(1);
            }
        } catch (SQLException e) {
            System.err.println("Error counting materials: " + e.getMessage());
            e.printStackTrace();
        }
        return 0;
    }

    public long countLowStock() {
        String sql;
        if ("materials".equals(tableName)) {
            sql = "SELECT COUNT(*) FROM materials WHERE quantity <= threshold AND is_active = 1";
        } else {
            sql = "SELECT COUNT(*) FROM " + tableName + " WHERE quantity <= threshold";
        }

        try (PreparedStatement stmt = prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            if (rs.next()) {
                return rs.getLong(1);
            }
        } catch (SQLException e) {
            System.err.println("Error counting low stock materials: " + e.getMessage());
            e.printStackTrace();
        }
        return 0;
    }

    public boolean updatePricePerUnit(int materialId, BigDecimal newPrice) {
        String sql = "UPDATE materials SET price_per_unit = ?, updated_at = ? WHERE id = ?";

        try (PreparedStatement stmt = prepareStatement(sql)) {
            stmt.setBigDecimal(1, newPrice);
            stmt.setTimestamp(2, Timestamp.valueOf(LocalDateTime.now()));
            stmt.setInt(3, materialId);

            return stmt.executeUpdate() > 0;
        } catch (SQLException e) {
            System.err.println("Error updating material price: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }
}   