/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlyquanan.view.dish;

import com.mycompany.quanlyquanan.controller.CategoryController;
import com.mycompany.quanlyquanan.controller.DishController;
import com.mycompany.quanlyquanan.model.Category;
import com.mycompany.quanlyquanan.model.Dish;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 *
 * @author Administrator
 */
public class QuanLyMonAnPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyMonAnPanel
     */
    private DishController dishController;
    private CategoryController categoryController;
    private DefaultTableModel tableModel;
    private Dish selectedDish;
    
    // UI Components
    private JPanel toolNav;
    private JLabel titleLabel;
    private JButton btnAdd, btnEdit, btnDelete, btnSearch, btnRefresh, btnRecipe;
    private JTextField searchField;
    private JComboBox<Category> categoryFilter;
    private JTable dishTable;
    private JScrollPane tableScrollPane;
    private JPanel detailPanel;
    
    // Detail components
    private JLabel lblId, lblName, lblCategory, lblPrice, lblCostPrice, lblPrepTime;
    private JLabel lblDescription, lblStatus, lblProfit, lblProfitPercent;
    private JTextField txtId, txtName, txtCategory, txtPrice, txtCostPrice, txtPrepTime;
    private JTextArea txtDescription;
    private JLabel statusValue, profitValue, profitPercentValue;
    private JLabel dishImageLabel;

    
    public QuanLyMonAnPanel() {
        this.dishController = new DishController();
        this.categoryController = new CategoryController();
        initComponents();
        setupTable();
        loadData();
        loadCategoryFilter();
    }
    
    this.dishController = new DishController();
        this.categoryController = new CategoryController();
        initComponents();
        setupTable();
        loadData();
        loadCategoryFilter();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
