/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlyquanan.view.Order;

import com.mycompany.quanlyquanan.model.Dish;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Dimension;
import javax.swing.*;

/**
 *
 * @author Tyler
 */
public class DishPicture extends javax.swing.JButton {

    /**
     * Creates new form DishPicture
     */
    public DishPicture() {
        setLayout(new BorderLayout());
        initComponents();
        setMaximumSize(new Dimension(190, 230));
    }
    
    public DishPicture(Dish d) {
        setLayout(new BorderLayout());
        initComponents();
        setDishName(d.getName());
        setDishImage(d);
        setMaximumSize(new Dimension(190, 230));
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dishName = new javax.swing.JLabel();
        dishImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        dishName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dishName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dishName.setText("jLabel1");
        dishName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dishName.setVerifyInputWhenFocusTarget(false);

        dishImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dishImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/hotpot.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dishName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dishImage, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(dishImage, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dishName)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void setDishName(String dn) {
        dishName.setText(dn);
    }
    
    public void setDishImage(Dish d) {
        dishImage.setIcon(new ImageIcon(getClass().getResource(d.getImageUrl())));
    }
    
    
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new DishPicture().setVisible(true);
                }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dishImage;
    private javax.swing.JLabel dishName;
    // End of variables declaration//GEN-END:variables
}
