/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlyquanan.view.Order;

import com.mycompany.quanlyquanan.controller.DishController;
import com.mycompany.quanlyquanan.controller.OrderController;
import com.mycompany.quanlyquanan.controller.OrderItemController;
import com.mycompany.quanlyquanan.controller.TableController;
import com.mycompany.quanlyquanan.model.Dish;
import com.mycompany.quanlyquanan.model.Order;
import com.mycompany.quanlyquanan.model.OrderItem;
import com.mycompany.quanlyquanan.model.Table;
import com.mycompany.quanlyquanan.utils.RedisPublisher;
import com.mycompany.quanlyquanan.utils.RedisSubscriber1;
import com.mycompany.quanlyquanan.utils.Session;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import redis.clients.jedis.JedisPubSub;

/**
 *
 * @author Tyler
 */
public class KitchenPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderPanel
     */
    private int selectedRow;
    private JButton xnBtn;
    private JButton pvBtn;
    private JButton ttBtn;
    private JButton hBtn;
    private List<JButton> categoryButtons = new ArrayList<>();
    private List<Order> canceledList = new ArrayList<>();
    private List<Order> servedList = new ArrayList<>();
    private List<Order> doneList = new ArrayList<>();
    private JButton currentCatBtn = xnBtn;
    private String place = "kitchen";
    private OrderButton currentSelectedPanel = null;
    Boolean isAdmin = Session.getInstance().isAdmin();

    
    public KitchenPanel() {
        initComponents();
        categoryPanel.setLayout(new BoxLayout(categoryPanel, BoxLayout.Y_AXIS));
        categoryPanel.setPreferredSize(new Dimension(200, Integer.MAX_VALUE));
        orderFunctions.setPreferredSize(new Dimension(Integer.MAX_VALUE, 74));
        addCategoryButons();
        
        // Adjust the dish selection pane
        oScroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        oScroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        oScroll.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        oScroll.getHorizontalScrollBar().setUI(new CustomScrollBarUI());
        
        oWrapper.setLayout(new FlowLayout(FlowLayout.LEFT, 10, 10));
        oWrapper.setBackground(Color.WHITE);
        createInitalOrderPanel();

        
        // Adjust dish table
        oDetailScroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        oDetailScroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        oDetailScroll.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        oDetailScroll.getHorizontalScrollBar().setUI(new CustomScrollBarUI());
       
        setUpODTable();
        
        
        selectedRow = -1;
        kDone.setEnabled(false);
        if(!isAdmin) {
            startListeningForOIUpdate();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderFunctions = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kCancel = new javax.swing.JButton();
        kConfirm = new javax.swing.JButton();
        kDone = new javax.swing.JButton();
        categoryPanel = new javax.swing.JPanel();
        oScroll = new javax.swing.JScrollPane();
        oWrapper = new javax.swing.JPanel();
        oPanel = new javax.swing.JPanel();
        oDetailScroll = new javax.swing.JScrollPane();
        oDetailTable = new com.mycompany.quanlyquanan.view.Reports.Table();

        orderFunctions.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kitchen");

        kCancel.setBackground(new java.awt.Color(255, 242, 242));
        kCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/delete-40.png"))); // NOI18N
        kCancel.setText("Cancel");
        kCancel.setBorder(null);
        kCancel.setBorderPainted(false);
        kCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kCancel.setFocusable(false);
        kCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kCancel.setOpaque(true);
        kCancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kCancelMouseClicked(evt);
            }
        });
        kCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kCancelActionPerformed(evt);
            }
        });

        kConfirm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/confirm.png"))); // NOI18N
        kConfirm.setText("Confirm");
        kConfirm.setBorder(null);
        kConfirm.setBorderPainted(false);
        kConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kConfirm.setFocusable(false);
        kConfirm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kConfirm.setOpaque(true);
        kConfirm.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kConfirmMouseClicked(evt);
            }
        });
        kConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kConfirmActionPerformed(evt);
            }
        });

        kDone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kDone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/table (1).png"))); // NOI18N
        kDone.setText("Done");
        kDone.setBorder(null);
        kDone.setBorderPainted(false);
        kDone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kDone.setFocusable(false);
        kDone.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kDone.setOpaque(true);
        kDone.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kDone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kDoneMouseClicked(evt);
            }
        });
        kDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kDoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout orderFunctionsLayout = new javax.swing.GroupLayout(orderFunctions);
        orderFunctions.setLayout(orderFunctionsLayout);
        orderFunctionsLayout.setHorizontalGroup(
            orderFunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderFunctionsLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304)
                .addComponent(kConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(kCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(kDone, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 338, Short.MAX_VALUE))
        );
        orderFunctionsLayout.setVerticalGroup(
            orderFunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderFunctionsLayout.createSequentialGroup()
                .addGroup(orderFunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderFunctionsLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(orderFunctionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(orderFunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kCancel)
                            .addComponent(kConfirm)
                            .addComponent(kDone))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        categoryPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout categoryPanelLayout = new javax.swing.GroupLayout(categoryPanel);
        categoryPanel.setLayout(categoryPanelLayout);
        categoryPanelLayout.setHorizontalGroup(
            categoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        categoryPanelLayout.setVerticalGroup(
            categoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        oScroll.setBackground(new java.awt.Color(255, 255, 255));

        oWrapper.setBackground(new java.awt.Color(255, 255, 255));

        oPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout oPanelLayout = new javax.swing.GroupLayout(oPanel);
        oPanel.setLayout(oPanelLayout);
        oPanelLayout.setHorizontalGroup(
            oPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
        oPanelLayout.setVerticalGroup(
            oPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 774, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout oWrapperLayout = new javax.swing.GroupLayout(oWrapper);
        oWrapper.setLayout(oWrapperLayout);
        oWrapperLayout.setHorizontalGroup(
            oWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oWrapperLayout.createSequentialGroup()
                .addComponent(oPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 149, Short.MAX_VALUE))
        );
        oWrapperLayout.setVerticalGroup(
            oWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        oScroll.setViewportView(oWrapper);

        oDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        oDetailScroll.setViewportView(oDetailTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orderFunctions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(categoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oDetailScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(orderFunctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(oDetailScroll)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kCancelMouseClicked
        // TODO add your handling code here:
           
    }//GEN-LAST:event_kCancelMouseClicked

    private void kCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kCancelActionPerformed
        // TODO add your handling code here:
        if (currentSelectedPanel == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một đơn để hủy.");
            return;
        }
        
        OrderController oc = new OrderController();
        OrderItemController oic = new OrderItemController();
        Order o = oc.getOrderById(currentSelectedPanel.getOrderId());
        o.setStatus("canceled");
        oc.udpate(o);
        List<OrderItem> ol = oic.getByOrderId(o.getId());
        for(OrderItem oi : ol) {
            oi.setStatus("canceled");
            oic.update(oi);
        }
        oPanel.remove(currentSelectedPanel);
        currentSelectedPanel = null;
        oPanel.revalidate();
        oPanel.repaint();
        canceledList.add(o);
        clearOTable();
        new Thread(() -> {
            if (checkTableUse(o)) {
                if(o.getTable_id() != 0) {
                    TableController tc = new TableController();
                    Table t = tc.getTableById(o.getTable_id());
                    t.setStatus("available");
                    tc.updateTable(t);
                } 
            }
        }).start();        
        
        
        if (!isAdmin){
            RedisPublisher.publish("cancel_order_channel", String.valueOf(o.getId()));
        }
        
    }//GEN-LAST:event_kCancelActionPerformed

    private boolean checkTableUse(Order o) {
        if(o.getTable_id() != 0) {
            OrderController oc = new OrderController();
            List<Order> ol = oc.getNPDSUOrder();

            for(Order o1: ol) {
                if (o1.getTable_id() == o.getTable_id())
                    return false;
            }
        }
        
        return true;
    }
    
    private void kConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kConfirmMouseClicked

        

        // TODO add your handling code here:
    }//GEN-LAST:event_kConfirmMouseClicked

    private void kConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kConfirmActionPerformed
        // TODO add your handling code here:
        if (currentSelectedPanel == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một đơn để xác nhận.");
            return;
        }
        
        OrderController oc = new OrderController();
        OrderItemController oic = new OrderItemController();
        Order o = oc.getOrderById(currentSelectedPanel.getOrderId());
        o.setStatus("preparing");
        oc.udpate(o);
        List<OrderItem> ol = oic.getByOrderId(o.getId());
        for(OrderItem oi : ol) {
            o.setStatus("cooking");
            oic.update(oi);
        }
        oPanel.remove(currentSelectedPanel);
        currentSelectedPanel = null;
        oPanel.revalidate();
        oPanel.repaint();
        
        clearOTable();
        if(!isAdmin) {
            RedisPublisher.publish("cooking_order_channel", String.valueOf(o.getId()));
        }
    }//GEN-LAST:event_kConfirmActionPerformed

    private void kDoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kDoneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_kDoneMouseClicked

    private void kDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kDoneActionPerformed
        // TODO add your handling code here:
        if (currentSelectedPanel == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một đơn để hoàn thành.");
            return;
        }
        
        OrderController oc = new OrderController();
        OrderItemController oic = new OrderItemController();
        Order o = oc.getOrderById(currentSelectedPanel.getOrderId());
        o.setStatus("done");
        oc.udpate(o);
        List<OrderItem> ol = oic.getByOrderId(o.getId());
        for(OrderItem oi : ol) {
            o.setStatus("done");
            oic.update(oi);
        }
        oPanel.remove(currentSelectedPanel);
        currentSelectedPanel = null;
        oPanel.revalidate();
        oPanel.repaint();
        doneList.add(o);
        clearOTable();
        
        if(!isAdmin) {
            RedisPublisher.publish("done_order_channel", String.valueOf(o.getId()));
        }  
    }//GEN-LAST:event_kDoneActionPerformed
    
// Thêm các nút category
    private void addCategoryButons(){
        xnBtn = createCatButton("Chờ xác nhận");
        pvBtn = createCatButton("Chờ chế biến");
        ttBtn = createCatButton("Đã xong");
        hBtn = createCatButton("Đã hủy");
        

        // Add all to list for easy access
        categoryButtons.addAll(Arrays.asList(xnBtn, pvBtn, ttBtn, hBtn));

        // Add buttons to panel with spacing
        categoryPanel.add(Box.createVerticalStrut(30));
        categoryPanel.add(xnBtn);
        xnBtn.addActionListener(e -> {
            kConfirm.setEnabled(true);
            kCancel.setEnabled(true);
            kDone.setEnabled(false);
            createInitalOrderPanel();
        });
        categoryPanel.add(Box.createVerticalStrut(30));
        categoryPanel.add(pvBtn);
        pvBtn.addActionListener(e -> {
            kConfirm.setEnabled(false);
            kCancel.setEnabled(true);
            kDone.setEnabled(true);
            createOrderPanelWithStatus("pv");
        });
        
    
        categoryPanel.add(Box.createVerticalStrut(30));
        categoryPanel.add(ttBtn);
        ttBtn.addActionListener(e -> {
            createOrderPanelWithStatus("tt");
            kConfirm.setEnabled(false);
            kCancel.setEnabled(false);
            kDone.setEnabled(false);
        });
        categoryPanel.add(Box.createVerticalStrut(30));
        categoryPanel.add(hBtn);
        hBtn.addActionListener(e -> {
            createOrderPanelHuy();
            kConfirm.setEnabled(false);
            kCancel.setEnabled(false);
            kDone.setEnabled(false);
        });
        

        // Style and add listeners
        for (JButton btn : categoryButtons) {
            btn.setBackground(Color.WHITE);
            btn.setFont(new Font("SansSerif", Font.PLAIN, 14));
            btn.addActionListener(e -> {
                highlightSelectedButton(btn);
                currentCatBtn = btn;
                clearOTable();
            });
        }

        // Set default selected
        highlightSelectedButton(xnBtn);
        currentCatBtn = xnBtn;

        categoryPanel.revalidate();
        categoryPanel.repaint();
    };
    
    private void highlightSelectedButton(JButton selectedBtn) {
        for (JButton btn : categoryButtons) {
            if (btn == selectedBtn) {
                btn.setBackground(new Color(255, 255, 204)); // Highlight
                btn.setFont(btn.getFont().deriveFont(Font.BOLD));
            } else {
                btn.setBackground(Color.WHITE); // Reset
                btn.setFont(btn.getFont().deriveFont(Font.PLAIN));
            }
        }
    }
    
    private void clearOTable(){
        DefaultTableModel model = (DefaultTableModel) oDetailTable.getModel();
        for (int row = 0; row < model.getRowCount(); row++) {
            for (int col = 0; col < model.getColumnCount(); col++) {
                model.setValueAt("", row, col);
            }
        }
    }
    
    private JButton createCatButton(String label) {
        JButton btn = new JButton(label);
        btn.setAlignmentX(Component.CENTER_ALIGNMENT);
        btn.setMaximumSize(new Dimension(180, 40)); // optional: uniform size
        btn.setFocusPainted(false);
        btn.setBackground(new Color(240, 240, 255));
        btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        return btn;
    };
    
    // Hiệu chỉnh UI oDetailTable
    private void setUpODTable(){
        oDetailTable.setFillsViewportHeight(true);
        oDetailTable.setOpaque(true);
        oDetailScroll.getViewport().setBackground(Color.WHITE);
        oDetailTable.setBorder(BorderFactory.createEmptyBorder());
        oDetailTable.setShowHorizontalLines(true);
        oDetailTable.setGridColor(Color.LIGHT_GRAY);
        oDetailTable.setRowSelectionAllowed(true);
        oDetailTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < oDetailTable.getColumnCount(); i++) {
            oDetailTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // Adjust table headers, fill table to the gap
        String[] columnNames = {"No.", "Dish Name", "Quantity", "Trạng thái"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // disables editing for all cells
            }
        };
        
        
        for (int i = 0; i < 30; i++) {
            model.addRow(new Object[] { "", "", "", ""});
        }
        oDetailTable.setModel(model);
        
        oDetailTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                selectedRow = oDetailTable.getSelectedRow();
            }
        });
        
        oDetailTable.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseMoved(MouseEvent e) {
                int row = oDetailTable.rowAtPoint(e.getPoint());
                if (row != -1) {
                    Object dishName = oDetailTable.getValueAt(row, 1); // Column 1: Dish Name
                    if (dishName != null && !dishName.toString().trim().isEmpty()) {
                        oDetailTable.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                        return;
                    }
                }
                oDetailTable.setCursor(Cursor.getDefaultCursor());
            }
        });
    }
    
    // Tạo UI đầu tiên khi mở trang
    private void createInitalOrderPanel() {
        oPanel.removeAll();
        oPanel.setLayout(new GridLayout(0, 3, 30, 30));
        oPanel.setPreferredSize(null);
        oPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        OrderController oc = new OrderController();
        List<Order> ol = oc.getAllNewOrder();
        
        for(Order o : ol) {
            JPanel oBtn = createOrderButton(o, oPanel, canceledList, servedList, oDetailTable, place);
            oPanel.add(oBtn);
        }
        
        oPanel.revalidate();
        oPanel.repaint();
    }
    
    // Tạo UI khi bấm Cat button
    private void createOrderPanelWithStatus(String status) {
        oPanel.removeAll();
        oPanel.setLayout(new GridLayout(0, 3, 30, 30));
        oPanel.setPreferredSize(null);
        oPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        OrderController oc = new OrderController();
        List<Order> ol = new ArrayList<>();
        if(status.equals("pv"))
            ol = oc.getAllPreparingOrder();
        
        if(status.equals("tt"))
            ol = doneList;
        
        for(Order o : ol) {
            JPanel oBtn = createOrderButton(o, oPanel, canceledList, servedList, oDetailTable, place);
            oPanel.add(oBtn);
        }
        
        oPanel.revalidate();
        oPanel.repaint();
    }
    
    private void createOrderPanelHuy() {
        oPanel.removeAll();
        oPanel.setLayout(new GridLayout(0, 3, 30, 30));
        oPanel.setPreferredSize(null);
        oPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        
        for(Order o : canceledList) {
            OrderButton oBtn = createOrderButton(o, oPanel, canceledList, servedList, oDetailTable, place);
            oPanel.add(oBtn);
        }
        
        oPanel.revalidate();
        oPanel.repaint();
    }
    
    private OrderButton createOrderButton(Order o, JPanel pane, List<Order> canceledList, List<Order> servedList, JTable oDetailTable, String place) {
        OrderButton oBtn = new OrderButton(o, oPanel, canceledList, servedList, oDetailTable, place);
            
            oBtn.addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent e) {
                    if (e.getClickCount() == 1 && SwingUtilities.isLeftMouseButton(e)) {
                        addDishToTable(o);
                        currentSelectedPanel = oBtn;
                    }
                }
            });
            
            
        return oBtn;
    }
    
    
    private void addDishToTable(Order o) {
        DefaultTableModel model = (DefaultTableModel) oDetailTable.getModel();

        // Clear existing data but keep row count
        for (int i = 0; i < model.getRowCount(); i++) {
            for (int j = 0; j < model.getColumnCount(); j++) {
                model.setValueAt("", i, j);
            }
        }

        OrderItemController oic = new OrderItemController();
        List<OrderItem> items = oic.getByOrderId(o.getId());
        DishController dc = new DishController();

        int index = 1;
        for (int i = 0; i < items.size() && i < model.getRowCount(); i++) {
            OrderItem oi = items.get(i);
            Dish dish = dc.getById(oi.getDish_id());

            model.setValueAt(index++, i, 0); // "No."
            model.setValueAt(dish.getName(), i, 1); // "Dish Name"
            model.setValueAt(oi.getQuantity(), i, 2); // "Quantity"
            model.setValueAt(o.getStatus(), i, 3);
        }
    }
    
    // Xử lý thông tin từ Redis
    private void startListeningForOIUpdate() {
        JedisPubSub listener = new JedisPubSub() {
            @Override
            public void onMessage(String channel, String message) {
                if ("new_order_channel".equals(channel)) {
                    int oId = Integer.parseInt(message);
                    System.out.println("New order arrive: " + oId);
                    String m = "Đơn hàng " + oId + " mới vừa được tạo! Bạn có muốn xem ngay không?";

                    SwingUtilities.invokeLater(() -> {
                        int choice = JOptionPane.showOptionDialog(
                            null,
                            m,
                            "Thông báo",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.INFORMATION_MESSAGE,
                            null,
                            new Object[] { "Xem", "Để sau" },
                            "Xem"
                        );

                        if (choice == JOptionPane.YES_OPTION || currentCatBtn == xnBtn) {
                            handleNewOrder(oId, choice == JOptionPane.YES_OPTION);
                        }

                    });
                }

                if ("cancel_order_channel1".equals(channel)) {
                    int oId = Integer.parseInt(message);
                    System.out.println("Order canceled by restaurant: " + oId);
                    OrderController oc = new OrderController();
                    Order o = oc.getOrderById(oId);
                    String m = "Đơn hàng " + oId + " vừa bị NHÀ HÀNG hủy! Bạn có muốn xem ngay không?";

                    SwingUtilities.invokeLater(() -> {
                        int choice = JOptionPane.showOptionDialog(
                            null,
                            m,
                            "Thông báo",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.INFORMATION_MESSAGE,
                            null,
                            new Object[] { "Xem", "Để sau" },
                            "Xem"
                        );

                        
                        handleCancelOrder(o, choice == JOptionPane.YES_OPTION);
                    });
                }
            }
        }; // ✅ Close the listener class here

        RedisSubscriber1 subscriber = new RedisSubscriber1();
        subscriber.subscribe(listener, "cancel_order_channel1", "new_order_channel");
    }
    
    // Handle new Order
    private void handleNewOrder(int orderId, boolean chooseYes) {
        createInitalOrderPanel();
        highlightSelectedButton(xnBtn);
        clearOTable();
        OrderController oc = new OrderController();
        Order o = oc.getOrderById(orderId);
        if (chooseYes)
            addDishToTable(o); 
    }
    
    // Handle cancel order từ nhà hàng
    private void handleCancelOrder(Order o, boolean chooseYes) {
        Component[] components = oPanel.getComponents();

        for (Component comp : components) {
            if (comp instanceof OrderButton) {
                OrderButton ob = (OrderButton) comp;
                if (ob.getOrderId() == o.getId()) {
                    oPanel.remove(ob);
                    break;
                }
            }
        }

        oPanel.revalidate();
        oPanel.repaint();
        canceledList.add(o);
        
        if (chooseYes) {
            highlightSelectedButton(hBtn);
            hBtn.doClick();
            addDishToTable(o);
        } else {
            if(currentCatBtn == hBtn) {
                JPanel oBtn = createOrderButton(o, oPanel, canceledList, servedList, oDetailTable, place);
                oPanel.add(oBtn);
                oPanel.revalidate();
                oPanel.repaint();
            }
        }
    }
    
//    public static void main(String[] args) {
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Kitchen Panel");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(1000, 700); // or use frame.pack() if layout is dynamic

            KitchenPanel kitchenPanel = new KitchenPanel();
            frame.setContentPane(kitchenPanel);

            frame.setLocationRelativeTo(null); // center on screen
            frame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel categoryPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kCancel;
    private javax.swing.JButton kConfirm;
    private javax.swing.JButton kDone;
    private javax.swing.JScrollPane oDetailScroll;
    private com.mycompany.quanlyquanan.view.Reports.Table oDetailTable;
    private javax.swing.JPanel oPanel;
    private javax.swing.JScrollPane oScroll;
    private javax.swing.JPanel oWrapper;
    private javax.swing.JPanel orderFunctions;
    // End of variables declaration//GEN-END:variables
}
