/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlyquanan.view.dish;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Insets;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.SwingConstants;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

import com.mycompany.quanlyquanan.controller.DishController;
import com.mycompany.quanlyquanan.model.Dish;
import com.mycompany.quanlyquanan.utils.ComponentStyleUtil;
import com.mycompany.quanlyquanan.utils.ImageUtils;
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

public class QuanLyMonAnPanel extends javax.swing.JPanel {

    

    private final DishController dishController = new DishController();
    private List<Dish> dishes = new ArrayList<>();
    private Dish selectedDish;
    private DefaultTableModel dishTableModel;
    private ButtonGroup statusGroup;

    public QuanLyMonAnPanel() {
        initComponents();
        //customStyle();

        statusGroup = new ButtonGroup();
        statusGroup.add(ipTrueMerge);
        statusGroup.add(ipFalseMerge1);
        ipTrueMerge.setEnabled(false);
        ipFalseMerge1.setEnabled(false);


        setupTable();
        setupTableSelection();
        loadAllDishes();
        this.revalidate();
        this.repaint();



    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolNav = new javax.swing.JPanel();
        txtSearchDish = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnDeleteDish = new javax.swing.JButton();
        btnAddDish = new javax.swing.JButton();
        btnEditDish = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnResetDish = new javax.swing.JButton();
        btnDeactivateDish = new javax.swing.JButton();
        btnActivateDish = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDish1 = new javax.swing.JTable();
        pnDishProfile = new javax.swing.JPanel();
        ipAvatar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ipId = new javax.swing.JLabel();
        ipName = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ipPrepTime = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ipPrice = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        ipDescription = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ipCategory = new javax.swing.JLabel();
        ipFalseMerge1 = new javax.swing.JRadioButton();
        ipTrueMerge = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        ipCost = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 244, 244));
        setPreferredSize(new java.awt.Dimension(1296, 745));

        toolNav.setBackground(new java.awt.Color(255, 255, 255));
        toolNav.setPreferredSize(new java.awt.Dimension(1061, 100));

        txtSearchDish.setPreferredSize(new java.awt.Dimension(200, 40));
        txtSearchDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchDishActionPerformed(evt);
            }
        });
        txtSearchDish.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchDishKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Quản lý Món Ăn");
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 22));

        btnDeleteDish.setBackground(new java.awt.Color(255, 242, 242));
        btnDeleteDish.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteDish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/delete-40.png"))); // NOI18N
        btnDeleteDish.setText("Delete");
        btnDeleteDish.setBorder(null);
        btnDeleteDish.setBorderPainted(false);
        btnDeleteDish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteDish.setFocusable(false);
        btnDeleteDish.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteDish.setOpaque(true);
        btnDeleteDish.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeleteDish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteDishMouseClicked(evt);
            }
        });
        btnDeleteDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDishActionPerformed(evt);
            }
        });

        btnAddDish.setBackground(new java.awt.Color(255, 242, 242));
        btnAddDish.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddDish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/plus-40.png"))); // NOI18N
        btnAddDish.setText("Add");
        btnAddDish.setBorder(null);
        btnAddDish.setBorderPainted(false);
        btnAddDish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddDish.setFocusable(false);
        btnAddDish.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddDish.setOpaque(true);
        btnAddDish.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddDish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddDishMouseClicked(evt);
            }
        });
        btnAddDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDishActionPerformed(evt);
            }
        });

        btnEditDish.setBackground(new java.awt.Color(255, 242, 242));
        btnEditDish.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditDish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/pencil-40.png"))); // NOI18N
        btnEditDish.setText("Edit");
        btnEditDish.setBorder(null);
        btnEditDish.setBorderPainted(false);
        btnEditDish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditDish.setFocusable(false);
        btnEditDish.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditDish.setOpaque(true);
        btnEditDish.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditDish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditDishMouseClicked(evt);
            }
        });
        btnEditDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDishActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/search-40.png"))); // NOI18N
        btnSearch.setBorder(null);
        btnSearch.setBorderPainted(false);
        btnSearch.setContentAreaFilled(false);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setFocusPainted(false);
        btnSearch.setFocusable(false);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnResetDish.setBackground(new java.awt.Color(244, 244, 244));
        btnResetDish.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnResetDish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/reset-password-40.png"))); // NOI18N
        btnResetDish.setText("Reset");
        btnResetDish.setBorder(null);
        btnResetDish.setBorderPainted(false);
        btnResetDish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetDish.setFocusable(false);
        btnResetDish.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnResetDish.setOpaque(true);
        btnResetDish.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnResetDish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetDishMouseClicked(evt);
            }
        });
        btnResetDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetDishActionPerformed(evt);
            }
        });

        btnDeactivateDish.setBackground(new java.awt.Color(244, 244, 244));
        btnDeactivateDish.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeactivateDish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/delete-user-40.png"))); // NOI18N
        btnDeactivateDish.setText("Deactivate");
        btnDeactivateDish.setBorder(null);
        btnDeactivateDish.setBorderPainted(false);
        btnDeactivateDish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeactivateDish.setFocusable(false);
        btnDeactivateDish.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeactivateDish.setOpaque(true);
        btnDeactivateDish.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeactivateDish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeactivateDishMouseClicked(evt);
            }
        });
        btnDeactivateDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeactivateDishActionPerformed(evt);
            }
        });

        btnActivateDish.setBackground(new java.awt.Color(244, 244, 244));
        btnActivateDish.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActivateDish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/verified-account-40.png"))); // NOI18N
        btnActivateDish.setText("Activate");
        btnActivateDish.setBorder(null);
        btnActivateDish.setBorderPainted(false);
        btnActivateDish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActivateDish.setFocusable(false);
        btnActivateDish.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActivateDish.setOpaque(true);
        btnActivateDish.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActivateDish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActivateDishMouseClicked(evt);
            }
        });
        btnActivateDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivateDishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toolNavLayout = new javax.swing.GroupLayout(toolNav);
        toolNav.setLayout(toolNavLayout);
        toolNavLayout.setHorizontalGroup(
            toolNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolNavLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddDish, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditDish, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteDish, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnResetDish, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActivateDish, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeactivateDish, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSearchDish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addGap(16, 16, 16))
        );
        toolNavLayout.setVerticalGroup(
            toolNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolNavLayout.createSequentialGroup()
                .addGroup(toolNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(toolNavLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(toolNavLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(toolNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddDish, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditDish, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteDish, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnResetDish, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeactivateDish, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActivateDish, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(toolNavLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(toolNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSearch)
                                    .addComponent(txtSearchDish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );

        jTableDish1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                /*{ new Integer(1), "Nguyên van a ", "Tk", "NguyênVana@gmail.com ", "Nhân viên",  new Boolean(true)},
                { new Integer(2), "Nguyên van a ", "pol", "NguyênVana@gmail.com ", "Nhân viên",  new Boolean(false)},
                { new Integer(3), "Nguyên van a ", "36", null, "Nhân viên",  new Boolean(true)}*/
            },
            new String [] {
                "ID", "Tên món", "Danh mục", "Giá bán", "Giá vốn", "Trạng thái", "Ngày tạo", "Ngày cập nhật"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableDish1);

        pnDishProfile.setBackground(new java.awt.Color(255, 255, 255));
        pnDishProfile.setMinimumSize(new java.awt.Dimension(351, 448));
        pnDishProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ipAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/employee/coala-160.png"))); // NOI18N
        pnDishProfile.add(ipAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 163, 175));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Món Ăn");
        pnDishProfile.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("ID:");
        pnDishProfile.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        ipId.setText("01");
        pnDishProfile.add(ipId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        ipName.setText("Trà Đá");
        pnDishProfile.add(ipName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Tên:");
        pnDishProfile.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 20));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Chi phí:");
        pnDishProfile.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        ipPrepTime.setText("2 phút");
        pnDishProfile.add(ipPrepTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Giá bán:");
        pnDishProfile.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        ipPrice.setText("12,000");
        pnDishProfile.add(ipPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 242, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Mô tả:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 15, -1, -1));

        ipDescription.setText("xxxxx");
        ipDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(ipDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 15, 170, 90));

        pnDishProfile.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 310, 110));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Danh Mục:");
        pnDishProfile.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        ipCategory.setText("Đồ uống");
        pnDishProfile.add(ipCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        ipFalseMerge1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ipFalseMerge1.setForeground(new java.awt.Color(102, 102, 102));
        ipFalseMerge1.setText("False");
        ipFalseMerge1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipFalseMerge1ActionPerformed(evt);
            }
        });
        pnDishProfile.add(ipFalseMerge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        ipTrueMerge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ipTrueMerge.setForeground(new java.awt.Color(0, 153, 51));
        ipTrueMerge.setText("True");
        ipTrueMerge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipTrueMergeActionPerformed(evt);
            }
        });
        pnDishProfile.add(ipTrueMerge, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Prep time:");
        pnDishProfile.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Active :");
        pnDishProfile.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        ipCost.setText("2,000");
        pnDishProfile.add(ipCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toolNav, javax.swing.GroupLayout.DEFAULT_SIZE, 1290, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnDishProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(pnDishProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtSearchDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchDishActionPerformed
        // TODO add your handling code here:
        searchDishes();
    }//GEN-LAST:event_txtSearchDishActionPerformed

    private void btnDeleteDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDishActionPerformed
            // TODO add your handling code here:
         deleteSelectedDish();
    }//GEN-LAST:event_btnDeleteDishActionPerformed

    private void btnAddDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDishActionPerformed
        // TODO add your handling code here:
        openCreateDishDialog();
       
    }//GEN-LAST:event_btnAddDishActionPerformed

    private void btnEditDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDishActionPerformed
        openEditDishDialog();
    }//GEN-LAST:event_btnEditDishActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        searchDishes();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnResetDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetDishActionPerformed
        // TODO add your handling code here:
         resetSearch();
    }//GEN-LAST:event_btnResetDishActionPerformed

    private void btnDeactivateDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeactivateDishActionPerformed
        // TODO add your handling code here:
        deactivateDish();
    }//GEN-LAST:event_btnDeactivateDishActionPerformed

    private void btnActivateDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivateDishActionPerformed
        // TODO add your handling code here:
        activateDish();
    }//GEN-LAST:event_btnActivateDishActionPerformed

    private void btnAddDishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddDishMouseClicked
        openCreateDishDialog();
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnAddDishMouseClicked

    private void btnEditDishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditDishMouseClicked
        // TODO add your handling code here:
      openEditDishDialog();
    }//GEN-LAST:event_btnEditDishMouseClicked

    private void btnDeleteDishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteDishMouseClicked
        // TODO add your handling code here:
           deleteSelectedDish();
    }//GEN-LAST:event_btnDeleteDishMouseClicked

    private void btnActivateDishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActivateDishMouseClicked
        activateDish();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActivateDishMouseClicked

    private void btnDeactivateDishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeactivateDishMouseClicked
        // TODO add your handling code here:
        deactivateDish();

    }//GEN-LAST:event_btnDeactivateDishMouseClicked

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        searchDishes();
        // TODO add your    handling code here:
    
    }//GEN-LAST:event_btnSearchMouseClicked

    private void txtSearchDishKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchDishKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            searchDishes();
        }

    }//GEN-LAST:event_txtSearchDishKeyPressed

    private void btnResetDishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetDishMouseClicked
        resetSearch();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetDishMouseClicked

    private void ipFalseMerge1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipFalseMerge1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipFalseMerge1ActionPerformed

    private void ipTrueMergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipTrueMergeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipTrueMergeActionPerformed
/*
        private void customStyle() {
        GroupLayout navLayout = (GroupLayout) toolNav.getLayout();
        navLayout.setAutoCreateGaps(true);
        navLayout.setAutoCreateContainerGaps(true);

        GroupLayout profileLayout = (GroupLayout) pnDishProfile.getLayout();
        profileLayout.setAutoCreateGaps(true);
        profileLayout.setAutoCreateContainerGaps(true);

        toolNav.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnDishProfile.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        JButton[] buttons = {btnDeleteDish, btnAddDish, btnEditDish, btnSearch,
            btnResetDish, btnDeactivateDish, btnActivateDish};
        for (JButton btn : buttons) {
            btn.setMargin(new Insets(5, 15, 5, 15));
        }

        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
    }
*/
        private void setupTable() {
        String[] columns = {"ID", "Tên món", "Danh mục", "Giá bán", "Giá vốn", "Trạng thái", "Ngày tạo", "Ngày cập nhật"};
        dishTableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTableDish1.setModel(dishTableModel);
        jTableDish1.setRowHeight(30);
        jTableDish1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
//        customsStyle();
            ComponentStyleUtil.styleTableScrollPane(jScrollPane2);
            ComponentStyleUtil.styleTable(jTableDish1);
            ComponentStyleUtil.enableTableSorting(jTableDish1);
            jTableDish1.getColumnModel().getColumn(5).setCellRenderer(new StatusCellRenderer());
            ComponentStyleUtil.styleSearchTextField(txtSearchDish);
    }

    private void setupTableSelection() {
        jTableDish1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int row = jTableDish1.getSelectedRow();
                    if (row >= 0 && row < jTableDish1.getRowCount()) {
                        selectedDish = dishes.get(jTableDish1.convertRowIndexToModel(row));
                        updateDishProfile();
                    }
                }
            }
        });
    }

    private void loadAllDishes() {
        dishes = dishController.getAll();
        refreshTable(dishes);
        selectedDish = null;
        updateDishProfile();
    }

    private void refreshTable(List<Dish> list) {
        dishTableModel.setRowCount(0);
        for (Dish d : list) {
            dishTableModel.addRow(new Object[]{
                d.getId(),
                d.getName(),
                d.getCategoryName(),
                d.getPrice(),
                d.getCostPrice(),
               // d.isAvailable(),
                d.isAvailable() ? "Đang bán" : "Ngừng bán",
                d.getCreatedAt(),
                d.getUpdatedAt()
            });
        }
    }

    private void searchDishes() {
        String keyword = txtSearchDish.getText().trim();
        if (keyword.isEmpty()) {
            loadAllDishes();
        } else {
            List<Dish> result = dishController.search(keyword);
            refreshTable(result);
        }
    }

    private void resetSearch() {
        txtSearchDish.setText("");
        loadAllDishes();
    }

    private void deleteSelectedDish() {
        if (selectedDish == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn món ăn");
            return;
        }
        if (dishController.delete(selectedDish.getId())) {
            loadAllDishes();
        }
    }

    private void openCreateDishDialog() {
        Frame frame = (Frame) SwingUtilities.getWindowAncestor(this);
        CreateDishDialog dialog = new CreateDishDialog(frame, true, this);
        dialog.setLocationRelativeTo(frame);
        dialog.setVisible(true);
        loadAllDishes();
    }

    private void openEditDishDialog() {
        if (selectedDish == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn món ăn");
            return;
        }
        Frame frame = (Frame) SwingUtilities.getWindowAncestor(this);
        EditDishDialog dialog = new EditDishDialog(frame, true, selectedDish, this);
        dialog.setLocationRelativeTo(frame);
        dialog.setVisible(true);
        loadAllDishes();
    }

    private void activateDish() {
        if (selectedDish == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn món ăn");
            return;
        }
        if (!selectedDish.isAvailable() && dishController.toggleAvailability(selectedDish.getId())) {
            loadAllDishes();
        }
    }

    private void deactivateDish() {
        if (selectedDish == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn món ăn");
            return;
        }
        if (selectedDish.isAvailable() && dishController.toggleAvailability(selectedDish.getId())) {
            loadAllDishes();
        }
    }

    private void updateDishProfile() {
        if (selectedDish == null) {
            ipAvatar.setIcon(new ImageIcon(getClass().getResource("/assets/images/login/hotpot.png")));
            ipId.setText("");
            ipName.setText("");
            ipCategory.setText("");
            ipCost.setText("");
            ipPrice.setText("");
            ipPrepTime.setText("");
            ipDescription.setText("");
            statusGroup.clearSelection();
            return;
        }

        if (selectedDish.getImageUrl() != null && !selectedDish.getImageUrl().isEmpty()) {
            ImageIcon icon = ImageUtils.loadImage(selectedDish.getImageUrl(), 160, 175);
            if (icon != null) {
                ipAvatar.setIcon(icon);
            } else {
                ipAvatar.setIcon(new ImageIcon(getClass().getResource("/assets/images/login/hotpot.png")));                
            }
        } else {
            ipAvatar.setIcon(new ImageIcon(getClass().getResource("/assets/images/login/hotpot.png")));
        }

        ipId.setText(String.valueOf(selectedDish.getId()));
        ipName.setText(selectedDish.getName());
        ipCategory.setText(selectedDish.getCategoryName());
        ipCost.setText(selectedDish.getCostPrice() != null ? selectedDish.getCostPrice().toString() : "");
        ipPrice.setText(selectedDish.getPrice() != null ? selectedDish.getPrice().toString() : "");
        ipPrepTime.setText(selectedDish.getPrepTime() + " phút");
        ipDescription.setText(selectedDish.getDescription() != null ? selectedDish.getDescription() : "");
        if (selectedDish.isAvailable()) {
            ipTrueMerge.setSelected(true);
        } else {
            ipFalseMerge1.setSelected(true);
        }
    }

    protected void customsStyle() {
        JTableHeader header = jTableDish1.getTableHeader();
        header.setBackground(new Color(248, 249, 250));
        header.setForeground(new Color(52, 58, 64));
        header.setFont(new Font("SansSerif", Font.BOLD, 12));
        header.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(222, 226, 230)));
        header.setPreferredSize(new Dimension(0, 45));
    }
    
    private static class StatusCellRenderer extends DefaultTableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            String status = value != null ? value.toString() : "";
            if (!isSelected) {
                if ("Đang bán".equals(status)) {
                    setForeground(new Color(46, 125, 50));
                } else if ("Ngừng bán".equals(status)) {
                    setForeground(Color.RED);
                } else {
                    setForeground(Color.BLACK);
                }
            }
            setText(status);
            return this;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivateDish;
    private javax.swing.JButton btnAddDish;
    private javax.swing.JButton btnDeactivateDish;
    private javax.swing.JButton btnDeleteDish;
    private javax.swing.JButton btnEditDish;
    private javax.swing.JButton btnResetDish;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel ipAvatar;
    private javax.swing.JLabel ipCategory;
    private javax.swing.JLabel ipCost;
    private javax.swing.JLabel ipDescription;
    private javax.swing.JRadioButton ipFalseMerge1;
    private javax.swing.JLabel ipId;
    private javax.swing.JLabel ipName;
    private javax.swing.JLabel ipPrepTime;
    private javax.swing.JLabel ipPrice;
    private javax.swing.JRadioButton ipTrueMerge;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDish1;
    private javax.swing.JPanel pnDishProfile;
    private javax.swing.JPanel toolNav;
    private javax.swing.JTextField txtSearchDish;
    // End of variables declaration//GEN-END:variables

    void refreshData() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


}
