/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlyquanan.view.material;


import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.table.JTableHeader;
import java.awt.Insets;
import java.awt.Insets;
import javax.swing.SwingConstants;

import com.mycompany.quanlyquanan.controller.MaterialController;
import com.mycompany.quanlyquanan.model.Material;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

import com.mycompany.quanlyquanan.controller.MaterialController;
import com.mycompany.quanlyquanan.model.Material;
import com.mycompany.quanlyquanan.utils.ComponentStyleUtil;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.Component;

/**
 *
 * @author Administrator
 */
public class QuanLyNguyenLieuPanel extends javax.swing.JPanel {

    private final MaterialController materialController = new MaterialController();
    private List<Material> materials = new ArrayList<>();
    private Material selectedMaterial;
    private DefaultTableModel materialTableModel;

    public QuanLyNguyenLieuPanel() {
        initComponents();
        customStyle();
        setupTable();
        setupTableSelection();
        loadAllMaterials();
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolNav = new javax.swing.JPanel();
        ipSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnDeactivateDish = new javax.swing.JButton();
        btnActivateDish = new javax.swing.JButton();
        btnReset1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnSapHet = new javax.swing.JButton();
        count = new javax.swing.JLabel();
        countActive = new javax.swing.JLabel();
        countSapHet = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 244, 244));

        toolNav.setBackground(new java.awt.Color(255, 255, 255));
        toolNav.setPreferredSize(new java.awt.Dimension(1188, 100));

        ipSearch.setPreferredSize(new java.awt.Dimension(200, 40));
        ipSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipSearchActionPerformed(evt);
            }
        });
        ipSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ipSearchKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel2.setText("Quản lý Nguyên Liệu");
        jLabel2.setMaximumSize(new java.awt.Dimension(20, 21));
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 21));

        btnDelete.setBackground(new java.awt.Color(255, 242, 242));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/delete-40.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(null);
        btnDelete.setBorderPainted(false);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setOpaque(true);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(255, 242, 242));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/plus-40.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setBorder(null);
        btnAdd.setBorderPainted(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusable(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setOpaque(true);
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 242, 242));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/pencil-40.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setBorder(null);
        btnEdit.setBorderPainted(false);
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setOpaque(true);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/search-40.png"))); // NOI18N
        btnSearch.setBorder(null);
        btnSearch.setBorderPainted(false);
        btnSearch.setContentAreaFilled(false);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setFocusPainted(false);
        btnSearch.setFocusable(false);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnDeactivateDish.setBackground(new java.awt.Color(244, 244, 244));
        btnDeactivateDish.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeactivateDish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/delete-user-40.png"))); // NOI18N
        btnDeactivateDish.setText("Deactivate");
        btnDeactivateDish.setBorder(null);
        btnDeactivateDish.setBorderPainted(false);
        btnDeactivateDish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeactivateDish.setFocusable(false);
        btnDeactivateDish.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeactivateDish.setOpaque(true);
        btnDeactivateDish.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeactivateDish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeactivateDishMouseClicked(evt);
            }
        });
        btnDeactivateDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeactivateDishActionPerformed(evt);
            }
        });

        btnActivateDish.setBackground(new java.awt.Color(244, 244, 244));
        btnActivateDish.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActivateDish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/verified-account-40.png"))); // NOI18N
        btnActivateDish.setText("Activate");
        btnActivateDish.setBorder(null);
        btnActivateDish.setBorderPainted(false);
        btnActivateDish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActivateDish.setFocusable(false);
        btnActivateDish.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActivateDish.setOpaque(true);
        btnActivateDish.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActivateDish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActivateDishMouseClicked(evt);
            }
        });
        btnActivateDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivateDishActionPerformed(evt);
            }
        });

        btnReset1.setBackground(new java.awt.Color(244, 244, 244));
        btnReset1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/reset-password-40.png"))); // NOI18N
        btnReset1.setText("Reset");
        btnReset1.setBorder(null);
        btnReset1.setBorderPainted(false);
        btnReset1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset1.setFocusable(false);
        btnReset1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReset1.setOpaque(true);
        btnReset1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReset1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReset1MouseClicked(evt);
            }
        });
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toolNavLayout = new javax.swing.GroupLayout(toolNav);
        toolNav.setLayout(toolNavLayout);
        toolNavLayout.setHorizontalGroup(
            toolNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolNavLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActivateDish, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeactivateDish, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 132, Short.MAX_VALUE)
                .addComponent(ipSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addGap(16, 16, 16))
        );
        toolNavLayout.setVerticalGroup(
            toolNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolNavLayout.createSequentialGroup()
                .addGroup(toolNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(toolNavLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(toolNavLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(toolNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeactivateDish, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActivateDish, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(toolNavLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(toolNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSearch)
                                    .addComponent(ipSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );

        jScrollPane1.setAlignmentX(0.0F);
        jScrollPane1.setAlignmentY(0.0F);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên Nguyên Liệu", "Đơn vị","Số lượng", "Giá/đơn vị","Ngưỡng", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnSapHet.setBackground(new java.awt.Color(255, 153, 51));
        btnSapHet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSapHet.setForeground(new java.awt.Color(255, 255, 255));
        btnSapHet.setText("Sắp Hết Hàng");
        btnSapHet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapHetActionPerformed(evt);
            }
        });

        count.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        count.setText("Tổng:");

        countActive.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        countActive.setText("Hoạt động:");

        countSapHet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        countSapHet.setText("Sắp hết:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(countActive, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(countSapHet, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSapHet)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSapHet, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(count)
                            .addComponent(countActive)
                            .addComponent(countSapHet))
                        .addGap(14, 14, 14))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolNav, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    protected void customsStyle (){
        JTableHeader header = jTable1.getTableHeader();
        header.setBackground(new Color(248, 249, 250));
        header.setForeground(new Color(52, 58, 64));
        header.setFont(new Font("SansSerif", Font.BOLD, 12));
        header.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(222, 226, 230)));
        header.setPreferredSize(new Dimension(0, 45));

        ComponentStyleUtil.styleTableScrollPane(jScrollPane1);
        ComponentStyleUtil.styleTable(jTable1);
        ComponentStyleUtil.enableTableSorting(jTable1);
        ComponentStyleUtil.styleSearchTextField(ipSearch);
        
        
    }
       
    private void ipSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipSearchActionPerformed
        // TODO add your handling code here:
        searchMaterials();
    }//GEN-LAST:event_ipSearchActionPerformed

    private void ipSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ipSearchKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            searchMaterials();
        }
    }//GEN-LAST:event_ipSearchKeyPressed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
         deleteSelectedMaterial();
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        deleteSelectedMaterial();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        openCreateMaterialDialog();
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        openCreateMaterialDialog();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        //openEditMaterialDialog();
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        openEditMaterialDialog();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        searchMaterials();
    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        searchMaterials();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnActivateDishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActivateDishMouseClicked
        activateMaterial();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActivateDishMouseClicked

    private void btnActivateDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivateDishActionPerformed
        // TODO add your handling code here:
        activateMaterial();
    }//GEN-LAST:event_btnActivateDishActionPerformed

    private void btnDeactivateDishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeactivateDishMouseClicked
        // TODO add your handling code here:
        deactivateMaterial();
    }//GEN-LAST:event_btnDeactivateDishMouseClicked

    private void btnDeactivateDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeactivateDishActionPerformed
        // TODO add your handling code here:
        deactivateMaterial();
    }//GEN-LAST:event_btnDeactivateDishActionPerformed

    private void btnReset1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReset1MouseClicked
        // TODO add your handling code here:
        resetSearch();
    }//GEN-LAST:event_btnReset1MouseClicked

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset1ActionPerformed
        // TODO add your handling code here:
        resetSearch();
    }//GEN-LAST:event_btnReset1ActionPerformed

    private void btnSapHetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapHetActionPerformed
        // TODO add your handling code here:
        showLowStockMaterials();
    }//GEN-LAST:event_btnSapHetActionPerformed
 
    private void customStyle() {
        GroupLayout navLayout = (GroupLayout) toolNav.getLayout();
        navLayout.setAutoCreateGaps(true);
        navLayout.setAutoCreateContainerGaps(true);

        GroupLayout statLayout = (GroupLayout) jPanel1.getLayout();
        statLayout.setAutoCreateGaps(true);
        statLayout.setAutoCreateContainerGaps(true);

        toolNav.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        JButton[] buttons = {btnDelete, btnAdd, btnEdit, btnSearch,
            btnDeactivateDish, btnActivateDish, btnReset1, btnSapHet};
        for (JButton btn : buttons) {
            btn.setMargin(new Insets(5, 15, 5, 15));
        }

        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        count.setHorizontalAlignment(SwingConstants.CENTER);
        countActive.setHorizontalAlignment(SwingConstants.CENTER);
        countSapHet.setHorizontalAlignment(SwingConstants.CENTER);
    }
        private void setupTable() {
        String[] columns = {"ID", "Tên Nguyên Liệu", "Đơn vị", "Số lượng", "Giá/đơn vị", "Ngưỡng", "Trạng Thái"};
        materialTableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable1.setModel(materialTableModel);
        jTable1.setRowHeight(30);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        
        jTable1.getColumnModel().getColumn(3).setCellRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                int modelRow = table.convertRowIndexToModel(row);
                if (!isSelected && modelRow < materials.size()) {
                    Material m = materials.get(modelRow);
                    if (m.isOutOfStock()) {
                        c.setForeground(Color.RED);
                    } else if (m.isLowStock()) {
                        c.setForeground(Color.ORANGE);
                    } else {
                        c.setForeground(table.getForeground());
                    }
                }
                return c;
            }
        });        
        customsStyle();
    }

    private void setupTableSelection() {
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int row = jTable1.getSelectedRow();
                    if (row >= 0 && row < jTable1.getRowCount()) {
                        selectedMaterial = materials.get(jTable1.convertRowIndexToModel(row));
                    }
                }
            }
        });
    }

    private void loadAllMaterials() {
        materials = materialController.getAll();
        refreshTable(materials);
        updateCounts();
    }

    private void refreshTable(List<Material> list) {
        materials = list;
        materialTableModel.setRowCount(0);
        for (Material m : list) {
            materialTableModel.addRow(new Object[]{
                m.getId(),
                m.getName(),
                m.getUnit(),
                m.getQuantity(),
                m.getPricePerUnit(),
                m.getThreshold(),
                m.isActive() ? "Hoạt động" : "Tạm ngưng"
            });
        }
        if (!list.isEmpty()) {
            jTable1.setRowSelectionInterval(0, 0);
            selectedMaterial = list.get(0);
        } else {
            selectedMaterial = null;
        }
    }

    private void updateCounts() {
        List<Material> all = materialController.getAll();
        int total = all.size();
        long active = all.stream().filter(Material::isActive).count();
        long low = all.stream().filter(m -> m.isActive() && m.isLowStock()).count();
        count.setText("Tổng: " + total);
        countActive.setText("Hoạt động: " + active);
        countSapHet.setText("Sắp hết: " + low);
    }

    private void searchMaterials() {
        String keyword = ipSearch.getText().trim();
        if (keyword.isEmpty()) {
            loadAllMaterials();
        } else {
            List<Material> result = materialController.search(keyword);
            refreshTable(result);
            updateCounts();
        }
    }

    private void resetSearch() {
        ipSearch.setText("");
        loadAllMaterials();
    }

    private void deleteSelectedMaterial() {
        if (selectedMaterial == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nguyên liệu");
            return;
        }
        if (materialController.delete(selectedMaterial.getId())) {
            loadAllMaterials();
        }
    }

    private void openCreateMaterialDialog() {
        Frame frame = (Frame) SwingUtilities.getWindowAncestor(this);
        ThemNguyenLieuDialog dialog = new ThemNguyenLieuDialog(frame);
        dialog.setLocationRelativeTo(frame);
        dialog.setVisible(true);
        loadAllMaterials();
    }

    private void openEditMaterialDialog() {
        if (selectedMaterial == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nguyên liệu");
            return;
        }
        Frame frame = (Frame) SwingUtilities.getWindowAncestor(this);
        SuaNguyenLieuDialog dialog = new SuaNguyenLieuDialog(frame, selectedMaterial);
        dialog.setLocationRelativeTo(frame);
        dialog.setVisible(true);
        loadAllMaterials();
    }

    private void activateMaterial() {
        if (selectedMaterial == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nguyên liệu");
            return;
        }
        if (!selectedMaterial.isActive()) {
            if (materialController.toggleStatus(selectedMaterial.getId())) {
                loadAllMaterials();
            }
        }
    }

    private void deactivateMaterial() {
        if (selectedMaterial == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nguyên liệu");
            return;
        }
        if (selectedMaterial.isActive()) {
            if (materialController.toggleStatus(selectedMaterial.getId())) {
                loadAllMaterials();
            }
        }
    }

    private void showLowStockMaterials() {
        List<Material> low = materialController.getLowStock();
        refreshTable(low);
        updateCounts();
    }
    
    private void alignTableBottom() {
        javax.swing.GroupLayout layout = (javax.swing.GroupLayout) this.getLayout();
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivateDish;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDeactivateDish;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnSapHet;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel count;
    private javax.swing.JLabel countActive;
    private javax.swing.JLabel countSapHet;
    private javax.swing.JTextField ipSearch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel toolNav;
    // End of variables declaration//GEN-END:variables
}
