/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/OkCancelDialog.java to edit this template
 */
package com.mycompany.quanlyquanan.view.material;

import com.mycompany.quanlyquanan.utils.ComponentStyleUtil;
import com.mycompany.quanlyquanan.view.material.QuanLyNguyenLieuPanel;
import java.awt.Frame;

import com.mycompany.quanlyquanan.controller.MaterialController;
import com.mycompany.quanlyquanan.model.Material;
import java.math.BigDecimal;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;




public class ThemNguyenLieuDialog extends javax.swing.JDialog {

    private final MaterialController materialController = new MaterialController();
    private final ButtonGroup statusGroup = new ButtonGroup();
    
    private boolean confirmed = false;

    public ThemNguyenLieuDialog(Frame parent) {

        initComponents();
        setModal(true);
        statusGroup.add(ipTrueMerge);
        statusGroup.add(ipFalseMerge1);
        ipTrueMerge.setSelected(true);
        ComponentStyleUtil.styleMainButton(bntAdd);
        ComponentStyleUtil.styleSecondButton(btnCancel);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnProfile = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        bntAdd = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtUnit = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtThread = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        ipTrueMerge = new javax.swing.JRadioButton();
        ipFalseMerge1 = new javax.swing.JRadioButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnProfile.setBackground(new java.awt.Color(255, 255, 255));
        pnProfile.setPreferredSize(new java.awt.Dimension(455, 600));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("THÊM NGUYÊN LIỆU MỚI");

        btnCancel.setBackground(new java.awt.Color(255, 51, 51));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Hủy");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        bntAdd.setBackground(new java.awt.Color(0, 153, 0));
        bntAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntAdd.setForeground(new java.awt.Color(255, 255, 255));
        bntAdd.setText("Thêm");
        bntAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntAddMouseClicked(evt);
            }
        });
        bntAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAddActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Tên Nguyên Liệu: (*)");

        txtName.setForeground(new java.awt.Color(102, 102, 102));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Đơn vị: (*)");

        txtUnit.setForeground(new java.awt.Color(102, 102, 102));
        txtUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Số lượng hiện tại: (*)");

        txtQty.setForeground(new java.awt.Color(102, 102, 102));
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Giá mỗi đơn vị: (*)");

        txtPrice.setForeground(new java.awt.Color(102, 102, 102));
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("Ngưỡng cảnh báo: (*)");

        txtThread.setForeground(new java.awt.Color(102, 102, 102));
        txtThread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThreadActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Trạng thái:");

        ipTrueMerge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ipTrueMerge.setForeground(new java.awt.Color(0, 153, 51));
        ipTrueMerge.setText("Hoạt động");
        ipTrueMerge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipTrueMergeActionPerformed(evt);
            }
        });

        ipFalseMerge1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ipFalseMerge1.setForeground(new java.awt.Color(102, 102, 102));
        ipFalseMerge1.setText("Tạm Ngưng");
        ipFalseMerge1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipFalseMerge1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnProfileLayout = new javax.swing.GroupLayout(pnProfile);
        pnProfile.setLayout(pnProfileLayout);
        pnProfileLayout.setHorizontalGroup(
            pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProfileLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(118, 118, 118))
            .addGroup(pnProfileLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnProfileLayout.createSequentialGroup()
                        .addComponent(ipTrueMerge)
                        .addGap(36, 36, 36)
                        .addComponent(ipFalseMerge1))
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtThread)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrice)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnProfileLayout.createSequentialGroup()
                            .addComponent(bntAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(154, 154, 154)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUnit)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtName)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtQty)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        pnProfileLayout.setVerticalGroup(
            pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfileLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addGap(27, 27, 27)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtThread, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipTrueMerge)
                    .addComponent(ipFalseMerge1))
                .addGap(30, 30, 30)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        getContentPane().add(pnProfile, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        dispose();
    }//GEN-LAST:event_closeDialog

    private void bntAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAddActionPerformed
        handleAdd();
    }//GEN-LAST:event_bntAddActionPerformed

    private void bntAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntAddMouseClicked
        handleAdd();
        // TODO add your handling code here:
    }//GEN-LAST:event_bntAddMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        dispose();
  
    }//GEN-LAST:event_btnCancelMouseClicked

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNameActionPerformed

    private void txtUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitActionPerformed

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtThreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThreadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThreadActionPerformed

    private void ipTrueMergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipTrueMergeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipTrueMergeActionPerformed

    private void ipFalseMerge1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipFalseMerge1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipFalseMerge1ActionPerformed

        private void handleAdd() {
        String name = txtName.getText().trim();
        String unit = txtUnit.getText().trim();
        String qtyText = txtQty.getText().trim();
        String priceText = txtPrice.getText().trim();
        String thresholdText = txtThread.getText().trim();

        BigDecimal quantity;
        BigDecimal pricePerUnit;
        BigDecimal threshold;

        try {
            quantity = new BigDecimal(qtyText);
            pricePerUnit = new BigDecimal(priceText);
            threshold = new BigDecimal(thresholdText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Số lượng, giá và ngưỡng cảnh báo phải là số hợp lệ",
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Material material = new Material();
        material.setName(name);
        material.setUnit(unit);
        material.setQuantity(quantity);
        material.setPricePerUnit(pricePerUnit);
        material.setThreshold(threshold);
        material.setActive(ipTrueMerge.isSelected());

        if (!material.isValid()) {
            JOptionPane.showMessageDialog(this,
                    material.getValidationError(),
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (materialController.create(material)) {
            dispose();
        }
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JRadioButton ipFalseMerge1;
    private javax.swing.JRadioButton ipTrueMerge;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel pnProfile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtThread;
    private javax.swing.JTextField txtUnit;
    // End of variables declaration//GEN-END:variables

    public boolean isConfirmed() {
      return confirmed;
    }
    


}
