/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlyquanan.view.Order;

import com.mycompany.quanlyquanan.controller.CategoryController;
import com.mycompany.quanlyquanan.controller.DishController;
import com.mycompany.quanlyquanan.controller.OrderController;
import com.mycompany.quanlyquanan.controller.OrderItemController;
import com.mycompany.quanlyquanan.controller.TableController;
import com.mycompany.quanlyquanan.model.Category;
import com.mycompany.quanlyquanan.model.Dish;
import com.mycompany.quanlyquanan.model.Employee;
import com.mycompany.quanlyquanan.model.Order;
import com.mycompany.quanlyquanan.model.OrderItem;
import com.mycompany.quanlyquanan.model.Table;
import com.mycompany.quanlyquanan.utils.RedisPublisher;
import com.mycompany.quanlyquanan.utils.Session;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import javax.swing.*;
import java.util.List;
import java.util.Map;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tyler
 */
public class POSPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private final Map<Dish, Integer> dishMap;
    private int selectedRow = -1;
    private int tableId;    
    private Session session;
    private Employee currentEm;
    private int newOrderId;
    boolean isAdmin = Session.getInstance().isAdmin();
    
    public POSPanel() {
        initComponents();
        dishMap = new HashMap<>();
        // Adjust the category menu
        categoryPanel.setLayout(new BoxLayout(categoryPanel, BoxLayout.Y_AXIS));
        categoryPanel.setPreferredSize(new Dimension(200, Integer.MAX_VALUE));
        posfunctions.setPreferredSize(new Dimension(Integer.MAX_VALUE, 74));
        addCategoryButons();
        
        // Adjust the dish selection pane
        dishPaneWrapper.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        dishPaneWrapper.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        dishPaneWrapper.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        dishPaneWrapper.getHorizontalScrollBar().setUI(new CustomScrollBarUI());
        
        wrapper.setLayout(new FlowLayout(FlowLayout.LEFT, 10, 10));
        wrapper.setBackground(Color.WHITE);
        createInitalDishPanel();

        
        // Adjust dish table
        dTableScroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        dTableScroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        dTableScroll.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        dTableScroll.getHorizontalScrollBar().setUI(new CustomScrollBarUI());
       
        setUpDTable();
        session = Session.getInstance();
        currentEm = session.getCurrentUser();
        if(currentEm != null) {
            String emDisplay = currentEm.getName() + "(" + currentEm.getId() + ")";
            nv2.setText(emDisplay);
        }
        
        b2.setText("Mang về");
        tableId = 0;
        dishMap.clear();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoryPanel = new javax.swing.JPanel();
        dishPaneWrapper = new javax.swing.JScrollPane();
        wrapper = new javax.swing.JPanel();
        dishPanel = new javax.swing.JPanel();
        posfunctions = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnOrderSearch = new javax.swing.JButton();
        dSearchText = new javax.swing.JTextField();
        dNew = new javax.swing.JButton();
        dDelete = new javax.swing.JButton();
        dConfirm = new javax.swing.JButton();
        dTakeAway = new javax.swing.JButton();
        b1 = new javax.swing.JLabel();
        nv1 = new javax.swing.JLabel();
        nv2 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        dEdit = new javax.swing.JButton();
        dSetTable = new javax.swing.JButton();
        dReset = new javax.swing.JButton();
        dTableScroll = new javax.swing.JScrollPane();
        dTable = new com.mycompany.quanlyquanan.view.Reports.Table();

        categoryPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout categoryPanelLayout = new javax.swing.GroupLayout(categoryPanel);
        categoryPanel.setLayout(categoryPanelLayout);
        categoryPanelLayout.setHorizontalGroup(
            categoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        categoryPanelLayout.setVerticalGroup(
            categoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        dishPaneWrapper.setBackground(new java.awt.Color(255, 255, 255));

        dishPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dishPanelLayout = new javax.swing.GroupLayout(dishPanel);
        dishPanel.setLayout(dishPanelLayout);
        dishPanelLayout.setHorizontalGroup(
            dishPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 819, Short.MAX_VALUE)
        );
        dishPanelLayout.setVerticalGroup(
            dishPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout wrapperLayout = new javax.swing.GroupLayout(wrapper);
        wrapper.setLayout(wrapperLayout);
        wrapperLayout.setHorizontalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dishPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(717, Short.MAX_VALUE))
        );
        wrapperLayout.setVerticalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dishPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        dishPaneWrapper.setViewportView(wrapper);

        posfunctions.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("POS");

        btnOrderSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOrderSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/search-40.png"))); // NOI18N
        btnOrderSearch.setBorder(null);
        btnOrderSearch.setBorderPainted(false);
        btnOrderSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrderSearch.setFocusable(false);
        btnOrderSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrderSearch.setOpaque(true);
        btnOrderSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOrderSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOrderSearchMouseClicked(evt);
            }
        });
        btnOrderSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderSearchActionPerformed(evt);
            }
        });

        dSearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dSearchTextActionPerformed(evt);
            }
        });
        dSearchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dSearchTextKeyPressed(evt);
            }
        });

        dNew.setBackground(new java.awt.Color(255, 242, 242));
        dNew.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/plus-40.png"))); // NOI18N
        dNew.setText("New");
        dNew.setBorder(null);
        dNew.setBorderPainted(false);
        dNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dNew.setFocusable(false);
        dNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dNew.setOpaque(true);
        dNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dNewMouseClicked(evt);
            }
        });
        dNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dNewActionPerformed(evt);
            }
        });

        dDelete.setBackground(new java.awt.Color(255, 242, 242));
        dDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/delete-40.png"))); // NOI18N
        dDelete.setText("Delete");
        dDelete.setBorder(null);
        dDelete.setBorderPainted(false);
        dDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dDelete.setFocusable(false);
        dDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dDelete.setOpaque(true);
        dDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dDeleteMouseClicked(evt);
            }
        });
        dDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dDeleteActionPerformed(evt);
            }
        });

        dConfirm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/confirm.png"))); // NOI18N
        dConfirm.setText("Confirm");
        dConfirm.setBorder(null);
        dConfirm.setBorderPainted(false);
        dConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dConfirm.setFocusable(false);
        dConfirm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dConfirm.setOpaque(true);
        dConfirm.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dConfirmMouseClicked(evt);
            }
        });
        dConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dConfirmActionPerformed(evt);
            }
        });

        dTakeAway.setBackground(new java.awt.Color(255, 255, 204));
        dTakeAway.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dTakeAway.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/table (1).png"))); // NOI18N
        dTakeAway.setText("Mang Về");
        dTakeAway.setBorder(null);
        dTakeAway.setBorderPainted(false);
        dTakeAway.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dTakeAway.setFocusable(false);
        dTakeAway.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dTakeAway.setOpaque(true);
        dTakeAway.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dTakeAway.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dTakeAwayMouseClicked(evt);
            }
        });
        dTakeAway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dTakeAwayActionPerformed(evt);
            }
        });

        b1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        b1.setText("Bàn:");

        nv1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nv1.setText("Nhân Viên:");

        nv2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nv2.setText("Nguyễn Văn A (2)");

        b2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b2.setText("Mang về");

        dEdit.setBackground(new java.awt.Color(255, 242, 242));
        dEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/pencil-40.png"))); // NOI18N
        dEdit.setText("Edit");
        dEdit.setBorder(null);
        dEdit.setBorderPainted(false);
        dEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dEdit.setFocusable(false);
        dEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dEdit.setOpaque(true);
        dEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dEditMouseClicked(evt);
            }
        });
        dEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dEditActionPerformed(evt);
            }
        });

        dSetTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dSetTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/table (1).png"))); // NOI18N
        dSetTable.setText("Bàn");
        dSetTable.setBorder(null);
        dSetTable.setBorderPainted(false);
        dSetTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dSetTable.setFocusable(false);
        dSetTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dSetTable.setOpaque(true);
        dSetTable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dSetTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dSetTableMouseClicked(evt);
            }
        });
        dSetTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dSetTableActionPerformed(evt);
            }
        });

        dReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/reset-password-40.png"))); // NOI18N
        dReset.setText("Reset");
        dReset.setBorder(null);
        dReset.setBorderPainted(false);
        dReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dReset.setFocusable(false);
        dReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dReset.setOpaque(true);
        dReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dResetMouseClicked(evt);
            }
        });
        dReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout posfunctionsLayout = new javax.swing.GroupLayout(posfunctions);
        posfunctions.setLayout(posfunctionsLayout);
        posfunctionsLayout.setHorizontalGroup(
            posfunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(posfunctionsLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOrderSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(dNew, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(dReset, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(dTakeAway)
                .addGap(18, 18, 18)
                .addComponent(dSetTable, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(posfunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nv1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(posfunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nv2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        posfunctionsLayout.setVerticalGroup(
            posfunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(posfunctionsLayout.createSequentialGroup()
                .addGroup(posfunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dReset)
                    .addComponent(dSetTable)
                    .addGroup(posfunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, posfunctionsLayout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(posfunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnOrderSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(dSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(posfunctionsLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addGroup(posfunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(posfunctionsLayout.createSequentialGroup()
                                    .addGroup(posfunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nv1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nv2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(posfunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(dNew)
                                .addComponent(dEdit)
                                .addComponent(dDelete)
                                .addComponent(dConfirm))))
                    .addComponent(dTakeAway))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        dTableScroll.setBackground(new java.awt.Color(255, 255, 255));

        dTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dTableScroll.setViewportView(dTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(categoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dishPaneWrapper, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(posfunctions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(posfunctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dishPaneWrapper, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(dTableScroll)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dTakeAwayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dTakeAwayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dTakeAwayActionPerformed

    private void dTakeAwayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dTakeAwayMouseClicked
        // TODO add your handling code here:
        tableId = 0;
        selectedRow = -1;
        b2.setText("Mang về");
        dTakeAway.setBackground(new Color(255,255,204));
        dSetTable.setBackground(Color.WHITE);
        revalidate();
        repaint();
    }//GEN-LAST:event_dTakeAwayMouseClicked

    
    
    private void btnOrderSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrderSearchActionPerformed

    
    private void btnOrderSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderSearchMouseClicked

        // TODO add your handling code here:
        String keyword = dSearchText.getText().trim();
        selectedRow = -1;
        if (keyword.isEmpty()) {
            createInitalDishPanel(); // Nếu rỗng thì load lại toàn bộ
        } else {
            DishController dc = new DishController();
                keyword = "%"+keyword+"%";
                List<Dish> dl = dc.getBySearch(keyword);
                createDishPanelSearch(dl);
        }
    }//GEN-LAST:event_btnOrderSearchMouseClicked

    private void dSearchTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dSearchTextKeyPressed
        // TODO add your handling code here:
        String keyword = dSearchText.getText().trim();
        if (keyword.isEmpty()) {
            createInitalDishPanel(); // Nếu rỗng thì load lại toàn bộ
        } else {
            DishController dc = new DishController();
                keyword = "%"+keyword+"%";
                List<Dish> dl = dc.getBySearch(keyword);
                createDishPanelSearch(dl);
        }

    }//GEN-LAST:event_dSearchTextKeyPressed

    private void dSearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dSearchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dSearchTextActionPerformed

    private void dConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dConfirmActionPerformed

    private void dConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dConfirmMouseClicked

        if (dishMap.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn món để lập đơn hàng.");
            return;
        } else {
            confirmOrder();
            showOrderConfirmationDialog(newOrderId, dishMap);
            clearDTable();
            dishMap.clear();
            
            // Gửi thông báo lên Redis
            if (!isAdmin) {
                RedisPublisher.publish("new_order_channel", String.valueOf(newOrderId));
            }
            

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_dConfirmMouseClicked

    private void dDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dDeleteActionPerformed

    private void dDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dDeleteMouseClicked
        // TODO add your handling code here:
        removeSelectedDish();
        selectedRow = -1;
        dTable.clearSelection();
    }//GEN-LAST:event_dDeleteMouseClicked

    private void dEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dEditActionPerformed

    private void dEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dEditMouseClicked
        // TODO add your handling code here:
        showEditQuantityDialog();
    }//GEN-LAST:event_dEditMouseClicked

    private void dNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dNewActionPerformed
        // TODO add your handling code here:
        dishMap.clear();
        clearDTable();
    }//GEN-LAST:event_dNewActionPerformed

    private void dNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dNewMouseClicked

        // TODO add your handling code here:
        dishMap.clear();
        clearDTable();
    }//GEN-LAST:event_dNewMouseClicked

    private void confirmOrder() {
        OrderController oc = new OrderController();
        Order o = new Order();
        o.setTable_id(this.tableId);
        // Cập nhật trạng thái của table 
        new Thread(() -> {
            if (this.tableId != 0) {
                TableController tc = new TableController();
                Table t = tc.getTableById(o.getTable_id());
                t.setStatus("serving");
                tc.updateTable(t);
            }
        }).start(); 
        
        
        BigDecimal total = BigDecimal.ZERO;
        for (Map.Entry<Dish, Integer> entry : dishMap.entrySet()) {
            Dish dish = entry.getKey();
            int qty = entry.getValue();
            BigDecimal price = dish.getPrice();
            BigDecimal amount = price.multiply(BigDecimal.valueOf(qty));
            total = total.add(amount);
        }
        o.setTotal_amount(total);
        
        int emId = currentEm == null ? 0 : currentEm.getId();
        o.setEmployee_id(emId); // Phải cập nhật id nhân viên ở đây
        OrderController os = new OrderController();
        // Bước 1. Tạo Order khi bấm Confirm
        oc.create(o);
        Order order = os.getLastestOrder();
        newOrderId = order.getId();
            
        // Bước 2. Tạo order_items của order vừa trên
        addOrderItemToDB(newOrderId);
    }
    
    // Tạo các orderItem cho order vừa tạo
    private void addOrderItemToDB(int orderId) {
        List<OrderItem> oil = createOrderItems(orderId);
        OrderItemController oic = new OrderItemController();
        for(OrderItem oi : oil) {
            oic.create(oi);
        }
    }
    
    private List<OrderItem> createOrderItems(int orderId) {
        List<OrderItem> orderItems = new ArrayList<>();

        for (Map.Entry<Dish, Integer> entry : dishMap.entrySet()) {
            Dish dish = entry.getKey();
            int quantity = entry.getValue();

            OrderItem item = new OrderItem(orderId, dish.getId(), quantity);
            orderItems.add(item);
        }

        return orderItems;
    }
    
    // UI sau khi order
    private void showOrderConfirmationDialog(int orderId, Map<Dish, Integer> dishMap) {
        JDialog dialog = new JDialog((JFrame) SwingUtilities.getWindowAncestor(this), "Đơn hàng đã tạo", true);
        dialog.setLayout(new BorderLayout(10, 10));
        BigDecimal total = BigDecimal.ZERO;

        // Header
        JLabel header = new JLabel("Đơn hàng #" + orderId + " đã được tạo thành công");
        header.setFont(new Font("Arial", Font.BOLD, 16));
        header.setHorizontalAlignment(SwingConstants.CENTER);
        dialog.add(header, BorderLayout.NORTH);

        // Table of dishes
        String[] columns = { "Tên món", "Số lượng", "Đơn giá", "Thành tiền" };
        DefaultTableModel model = new DefaultTableModel(columns, 0);

        for (Map.Entry<Dish, Integer> entry : dishMap.entrySet()) {
            Dish dish = entry.getKey();
            int qty = entry.getValue();
            BigDecimal price = dish.getPrice();
            BigDecimal amount = price.multiply(BigDecimal.valueOf(qty));
            total = total.add(amount);

            model.addRow(new Object[] {
                dish.getName(),
                qty,
                String.format("%,.0f₫", price),
                String.format("%,.0f₫", amount)
            });
            
            
        }
        
        model.addRow(new Object[] {
                "Tổng tiền",
                "",
                "",
                String.format("%,.0f₫", total)
            });

        JTable table = new JTable(model);
        table.setEnabled(false);
        table.setRowHeight(24);
        JScrollPane scrollPane = new JScrollPane(table);
        dialog.add(scrollPane, BorderLayout.CENTER);

        // Buttons
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 20, 10));
        JButton stayBtn = new JButton("OK");


        stayBtn.addActionListener(e -> {
            dialog.dispose();
            clearDTable();
            dishMap.clear();
        });

        buttonPanel.add(stayBtn);
        dialog.add(buttonPanel, BorderLayout.SOUTH);

        dialog.setSize(500, 400);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }
    
    private void dSetTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dSetTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dSetTableMouseClicked

    private void dSetTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dSetTableActionPerformed
        // TODO add your handling code here:
        TableController tc = new TableController();
        List<Table> tl = tc.getAllTables();
        showTableDialog(tl);
    }//GEN-LAST:event_dSetTableActionPerformed

    private void dResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dResetMouseClicked
        // TODO add your handling code here:
        dishMap.clear();
        clearDTable();
    }//GEN-LAST:event_dResetMouseClicked

    private void dResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dResetActionPerformed

    // Dọn sạch bảng
    private void clearDTable(){
        DefaultTableModel model = (DefaultTableModel) dTable.getModel();
        for (int row = 0; row < model.getRowCount(); row++) {
            for (int col = 0; col < model.getColumnCount(); col++) {
                model.setValueAt("", row, col);
            }
        }
    }
    
    // Hiện popup để chọn bàn
    private void showTableDialog(List<Table> tableList) {
        JDialog dialog = new JDialog((JFrame) SwingUtilities.getWindowAncestor(this), "Chọn bàn", true);
        dialog.setLayout(new BorderLayout());

        JPanel gridPanel = new JPanel(new GridLayout(0, 4, 10, 10)); // 4 columns

        for (Table table : tableList) {
            JButton tableBtn = new JButton(table.getName());
            tableBtn.setBackground(Color.GREEN);
            tableBtn.setForeground(Color.WHITE);
            tableBtn.setFocusPainted(false);

            tableBtn.addActionListener(e -> {
                tableId = table.getId();
                b2.setText(table.getName());
                b2.revalidate();
                b2.repaint();
                dialog.dispose();
                dSetTable.setBackground(new Color(255,255,209));
                dTakeAway.setBackground(Color.WHITE);
                revalidate();
                repaint();
            });

            gridPanel.add(tableBtn);
        }

        dialog.add(new JLabel("Chọn bàn để phục vụ:"), BorderLayout.NORTH);
        dialog.add(gridPanel, BorderLayout.CENTER);

        dialog.setSize(400, 300);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }
        
    // Hiện bảng popup để điều chỉnh quantity
    private void showEditQuantityDialog() {
        int selectedRow = dTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một món để chỉnh sửa.");
            return;
        }

        JDialog dialog = new JDialog((JFrame) SwingUtilities.getWindowAncestor(this), "Chỉnh sửa số lượng", true);
        dialog.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        JLabel label = new JLabel("Nhập số lượng mới:");
        JTextField quantityField = new JTextField(10);

        JButton clearBtn = new JButton("Clear");
        JButton deleteBtn = new JButton("<");
        JButton confirmBtn = new JButton("Confirm");
        
        JPanel numpadPanel = new JPanel(new GridLayout(4, 3, 5, 5));
        String[] digits = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "0" };

        for (String digit : digits) {
            JButton btn = new JButton(digit);
            btn.addActionListener(e -> quantityField.setText(quantityField.getText() + digit));
            numpadPanel.add(btn);
        }


        // Add components
        

        // Label and TextField
        gbc.gridx = 0; gbc.gridy = 0;
        dialog.add(label, gbc);

        gbc.gridx = 1; // assuming you want it beside the label
        dialog.add(quantityField, gbc);

        // Numpad (should come next)
        gbc.gridx = 0; gbc.gridy = 1; gbc.gridwidth = 2;
        dialog.add(numpadPanel, gbc);

        // Clear and Delete buttons
        gbc.gridwidth = 1; // reset gridwidth
        gbc.gridx = 0; gbc.gridy = 2;
        dialog.add(clearBtn, gbc);

        gbc.gridx = 1;
        dialog.add(deleteBtn, gbc);

        // Confirm button
        gbc.gridx = 0; gbc.gridy = 3; gbc.gridwidth = 2;
        dialog.add(confirmBtn, gbc);


        // Button actions
        clearBtn.addActionListener(e -> quantityField.setText(""));

        deleteBtn.addActionListener(e -> {
            String currentText = quantityField.getText();
            if (!currentText.isEmpty()) {
                quantityField.setText(currentText.substring(0, currentText.length() - 1));
            }
        });


        confirmBtn.addActionListener(e -> {
            try {
                int newQty = Integer.parseInt(quantityField.getText());
                if (newQty <= 0) throw new NumberFormatException();

                dTable.setValueAt(newQty, selectedRow, 2); // Quantity column
                double price = Double.parseDouble(dTable.getValueAt(selectedRow, 3).toString());
                dTable.setValueAt(price * newQty, selectedRow, 4); // Amount column

                // Update dishList
                for (Dish dish : dishMap.keySet()) {
                    if (dish.getName().equals(dTable.getValueAt(selectedRow, 1))) {
                        dishMap.put(dish, newQty);
                        break;
                    }
                }

                dialog.dispose();
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(dialog, "Vui lòng nhập số hợp lệ.");
            }
        });

    dialog.pack();
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
}
    private void removeSelectedDish(){
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một món để xóa.");
            return;
        }
        
        String dishName = (String) dTable.getValueAt(selectedRow, 1);
        dishMap.entrySet().removeIf(entry -> entry.getKey().getName().equals(dishName));
        
        // Delete row and move up
        DefaultTableModel model = (DefaultTableModel) dTable.getModel();
        int index = 1;
        model.removeRow(selectedRow);
        for (int i = 0; i < model.getRowCount(); i++) {
            String dn = (String) model.getValueAt(i, 1); // Column 1: Dish Name
            if (dn != null && !dn.trim().isEmpty()) {
                model.setValueAt(index++, i, 0); // Column 0: No.
            } else {
                model.setValueAt("", i, 0); // Clear index for empty rows
            }
        }
    }
        
    // Tạo menu phân loại thức ăn
    private void addCategoryButons() {
        CategoryController cc = new CategoryController();
        List<Category> catList = cc.getAllActive();
        catList.sort(Comparator.comparingInt(Category::getId));
        
        JButton allBtn = createCatButton("All Category");
        allBtn.addActionListener(e -> {
            createInitalDishPanel();
        });
        categoryPanel.add(Box.createVerticalStrut(30));
        categoryPanel.add(allBtn);
        
        for (Category cat : catList) {
            JButton btn = createCatButton(cat.getName());
            
            // Add action listener if needed
            btn.addActionListener(e -> {
                System.out.println("Selected: " + cat.getName());
                createDishPanelWithCatId(cat.getId());
            });

            categoryPanel.add(Box.createVerticalStrut(30)); // spacing
            categoryPanel.add(btn);
        }
        
        categoryPanel.add(Box.createVerticalStrut(50));
        
        categoryPanel.revalidate();
        categoryPanel.repaint();
    }
    
    private JButton createCatButton(String label) {
        JButton btn = new JButton(label);
        btn.setAlignmentX(Component.CENTER_ALIGNMENT);
        btn.setMaximumSize(new Dimension(180, 40)); // optional: uniform size
        btn.setFocusPainted(false);
        btn.setBackground(new Color(240, 240, 255));
        btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        return btn;
    };
    
    private void createInitalDishPanel() {
        dishPanel.removeAll();
        dishPanel.setLayout(new GridLayout(0, 3, 30, 30));
        dishPanel.setPreferredSize(null);
        dishPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        DishController dc = new DishController();
        List<Dish> dl = dc.getAllAvailable();
        for(Dish d : dl) {
            JButton dishBtn = new DishPicture(d);
            dishBtn.addActionListener(e -> { 
                System.out.println("Choose " + d.getName());
                addDishToTable(d);
                dTable.clearSelection();
            });
            dishPanel.add(dishBtn);
        }
        dishPanel.revalidate();
        dishPanel.repaint();
    }
    
    private void createDishPanelWithCatId(int catId) {
        dishPanel.removeAll();
        dishPanel.setLayout(new GridLayout(0, 3, 30, 30));
        dishPanel.setPreferredSize(null);
        dishPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        DishController dc = new DishController();
        List<Dish> dl = dc.getByCategory(catId);
        for(Dish d : dl) {
            JButton dishBtn = new DishPicture(d);
            dishBtn.addActionListener(e -> { 
                System.out.println("Choose " + d.getName());
                addDishToTable(d);
                dTable.clearSelection();
            });
            dishPanel.add(dishBtn);
        }
        dishPanel.revalidate();
        dishPanel.repaint();
    }
    
    private void createDishPanelSearch(List<Dish> dList) {
        dishPanel.removeAll();
        dishPanel.setLayout(new GridLayout(0, 3, 30, 30));
        dishPanel.setPreferredSize(null);
        dishPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        
        for(Dish d : dList) {
            JButton dishBtn = new DishPicture(d);
            dishBtn.addActionListener(e -> { 
                System.out.println("Choose " + d.getName());
                addDishToTable(d);
                dTable.clearSelection();
            });
            dishPanel.add(dishBtn);
        }
        
        dishPanel.revalidate();
        dishPanel.repaint();
    }
    
    // chỉnh UI bảng order
    private void setUpDTable(){
        dTable.setFillsViewportHeight(true);
        dTable.setOpaque(true);
        dTableScroll.getViewport().setBackground(Color.WHITE);
        dTable.setBorder(BorderFactory.createEmptyBorder());
        dTable.setShowHorizontalLines(true);
        dTable.setGridColor(Color.LIGHT_GRAY);
        dTable.setRowSelectionAllowed(true);
        dTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < dTable.getColumnCount(); i++) {
            dTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // Adjust table headers, fill table to the gap
        String[] columnNames = {"No.", "Dish Name", "Quantity", "Price", "Amount" };
        DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // disables editing for all cells
            }
        };
        
        
        for (int i = 0; i < 30; i++) {
            model.addRow(new Object[] { "", "", "", "", "" });
        }
        dTable.setModel(model);
        
        dTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                selectedRow = dTable.getSelectedRow();
            }
        });
        
        dTable.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseMoved(MouseEvent e) {
                int row = dTable.rowAtPoint(e.getPoint());
                if (row != -1) {
                    Object dishName = dTable.getValueAt(row, 1); // Column 1: Dish Name
                    if (dishName != null && !dishName.toString().trim().isEmpty()) {
                        dTable.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                        return;
                    }
                }
                dTable.setCursor(Cursor.getDefaultCursor());
            }
        });
    }
    
    // Thêm món ăn vào bàn
    private void addDishToTable(Dish d) {
          DefaultTableModel model = (DefaultTableModel) dTable.getModel();

        if (dishMap.containsKey(d)) {
            // Dish already exists — increment quantity
            int quantity = dishMap.get(d) + 1;
            dishMap.put(d, quantity);

            // Find and update the row
            for (int i = 0; i < model.getRowCount(); i++) {
                String name = (String) model.getValueAt(i, 1); // Column 1: Dish Name
                if (name.equals(d.getName())) {
                    model.setValueAt(quantity, i, 2); // Column 2: Quantity
                    model.setValueAt(d.getPrice().multiply(BigDecimal.valueOf(quantity)), i, 4); // Column 4: Amount
                    return;
                }
            }
        } else {
            // New dish — find first empty row
            for (int i = 0; i < model.getRowCount(); i++) {
                String name = (String) model.getValueAt(i, 1);
                if (name == null || name.trim().isEmpty()) {
                    dishMap.put(d, 1);
                    model.setValueAt(i + 1, i, 0); // No.
                    model.setValueAt(d.getName(), i, 1);
                    model.setValueAt(1, i, 2); // Quantity
                    model.setValueAt(d.getPrice(), i, 3); // Price
                    model.setValueAt(d.getPrice(), i, 4); // Amount
                    return;
                }
            }
        }

    }
    
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                JFrame frame = new JFrame("POS Demo");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setSize(800, 600); // hoặc dùng frame.pack() nếu layout tự co giãn

                POSPanel panel = new POSPanel();
                frame.setContentPane(panel);

                frame.setLocationRelativeTo(null); // căn giữa màn hình
                frame.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JButton btnOrderSearch;
    private javax.swing.JPanel categoryPanel;
    private javax.swing.JButton dConfirm;
    private javax.swing.JButton dDelete;
    private javax.swing.JButton dEdit;
    private javax.swing.JButton dNew;
    private javax.swing.JButton dReset;
    private javax.swing.JTextField dSearchText;
    private javax.swing.JButton dSetTable;
    private com.mycompany.quanlyquanan.view.Reports.Table dTable;
    private javax.swing.JScrollPane dTableScroll;
    private javax.swing.JButton dTakeAway;
    private javax.swing.JScrollPane dishPaneWrapper;
    private javax.swing.JPanel dishPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nv1;
    private javax.swing.JLabel nv2;
    private javax.swing.JPanel posfunctions;
    private javax.swing.JPanel wrapper;
    // End of variables declaration//GEN-END:variables
}
