/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlyquanan.view.Reports;

import com.mycompany.quanlyquanan.controller.ExpenseReceiptController;
import com.mycompany.quanlyquanan.controller.OrderController;
import com.mycompany.quanlyquanan.model.ModelCard;
import java.awt.Color;
import javax.swing.Icon;
import jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons;
import jiconfont.swing.IconFontSwing;

/**
 *
 * @author macos
 */
public class CardPanel extends javax.swing.JPanel {

    ExpenseReceiptController expenseController;
    OrderController orderController;
    /**
     * Creates new form DashboardPanel
     */
    public CardPanel() {
        initComponents();
        IconFontSwing.register(GoogleMaterialDesignIcons.getIconFont());
        initData();
    }
    
    public void initData(){
        initCardData();
    }

    //[TODO] - cần lấy dữ liệu từ database
    // Hiện tại chỉ là dữ liệu mẫu
    public void initCardData(){
        double totalExpense, totalIncome, revenue;
        expenseController = new ExpenseReceiptController();
        orderController = new OrderController();
        Icon icon1 = IconFontSwing.buildIcon(GoogleMaterialDesignIcons.ACCOUNT_BALANCE_WALLET, 60, new Color(255,255,255,100));
        totalIncome = orderController.getTodayTotalAmount();
        card1.setData(new ModelCard("Doanh thu", totalIncome, icon1));

        Icon icon2 = IconFontSwing.buildIcon(GoogleMaterialDesignIcons.MONETIZATION_ON, 60, new Color(255,255,255,100));
        totalExpense = expenseController.getTodayTotalExpense();
        card2.setData(new ModelCard("Chi phí", totalExpense, icon2));

        Icon icon3 = IconFontSwing.buildIcon(GoogleMaterialDesignIcons.SHOW_CHART, 60, new Color(255,255,255,100));
        revenue = totalIncome - totalExpense;
        card3.setData(new ModelCard("Lợi nhuận", revenue, icon3));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card1 = new com.mycompany.quanlyquanan.view.Reports.CardGradient();
        card2 = new com.mycompany.quanlyquanan.view.Reports.CardGradient();
        card3 = new com.mycompany.quanlyquanan.view.Reports.CardGradient();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(829, 133));

        card1.setBackground(new java.awt.Color(205, 139, 237));
        card1.setColorGradient(new java.awt.Color(255, 153, 153));

        card2.setBackground(new java.awt.Color(102, 204, 255));
        card2.setColorGradient(new java.awt.Color(255, 204, 255));

        card3.setBackground(new java.awt.Color(255, 204, 102));
        card3.setForeground(new java.awt.Color(255, 204, 153));
        card3.setColorGradient(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(card1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(card2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(card3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.quanlyquanan.view.Reports.CardGradient card1;
    private com.mycompany.quanlyquanan.view.Reports.CardGradient card2;
    private com.mycompany.quanlyquanan.view.Reports.CardGradient card3;

    public void reloadData() {
        initCardData();
    }
    // End of variables declaration//GEN-END:variables
}
